define(function (require, exports, module) {
    'use strict';

	const today = new Date();
	const day = String(today.getDate()).padStart(2, '0');
	const month = String(today.getMonth() + 1).padStart(2, '0'); // months start at 0
	const year = today.getFullYear();
	const currentDate = `${day}-${month}-${year}`;


    var snippets = {
		"tagattr": {
			"id": "id=\"#focus\"",
			"class": "class=\"#focus\"",
			"title": "title=\"#focus\"",
		},		
		"inattr": {
			"zoom": "zoom",
			"fade": "fade"
		},
		"main-header-tagattr": { 
			"hero-effect-zoom": "hero-effect=\"zoom\"",
			"hero-timing": "hero-timing=\"#focus\"",
			"hero-overlay": "hero-overlay=\"#focus\"",
			"class": { 
				"full": "full",
				"controlls": "controlls"			
			}
		},		
		"hero-slider-tagattr": { 
			"hero-effect-zoom": "hero-effect=\"zoom\"",
			"hero-timing": "hero-timing=\"#focus\"",
			"hero-overlay": "hero-overlay=\"#focus\"",
			"class": { 
				"dots": "dots",
				"controlls": "controlls"			
			}
		},
		version: {
			"version": "<?= time(); ?>",
			"?version": "<?= time(); ?>",
		},		
		inclass: {
			"skin-body": "skin.body",
			"skin-main": "skin.main",
			"skin-sub": "skin.sub",
			"skin-txt": "skin.txt",
			"skin-light": "skin.light",
			"skin-dark": "skin.dark",
			"skin-primary": "skin.primary",
			"skin-secondary": "skin.secondary",
			"skin-warning": "skin.warning",
			"skin-error": "skin.error",
			"skin-danger": "skin.danger",
			"skin-info": "skin.info",
			"skin-success": "skin.success",
			"skin-red": "skin.red",
			"skin-amber": "skin.amber",
			"skin-orange": "skin.orange",
			"skin-yellow": "skin.yellow",
			"skin-lime": "skin.lime",
			"skin-green": "skin.green",
			"skin-sky": "skin.sky",
			"skin-blue": "skin.blue",
			"skin-indigo": "skin.indigo",
			"skin-violet": "skin.violet",
			"skin-pink": "skin.pink",
			"skin-purple": "skin.purple",
			"skin-cyan": "skin.cyan",
			"skin-teal": "skin.teal",
			"skin-black": "skin.black",
			"skin-white": "skin.white",
			"skin-grey": "skin.grey",
			"skin-sepia": "skin.sepia",
			"skin-neon-green": "skin.neon.green",
			"skin-neon-orange": "skin.neon.orange",
			"skin-neon-blue": "skin.neon.blue",
			"skin-neon-yellow": "skin.neon.yellow",			
			"is-body": "is.body",
			"is-main": "is.main",
			"is-sub": "is.sub",
			"is-txt": "is.txt",
			"is-light": "is.light",
			"is-dark": "is.dark",
			"is-primary": "is.primary",
			"is-secondary": "is.secondary",
			"is-warning": "is.warning",
			"is-error": "is.error",
			"is-danger": "is.danger",
			"is-info": "is.info",
			"is-success": "is.success",
			"is-red": "is.red",
			"is-amber": "is.amber",
			"is-orange": "is.orange",
			"is-yellow": "is.yellow",
			"is-lime": "is.lime",
			"is-green": "is.green",
			"is-sky": "is.sky",
			"is-blue": "is.blue",
			"is-indigo": "is.indigo",
			"is-violet": "is.violet",
			"is-pink": "is.pink",
			"is-purple": "is.purple",
			"is-cyan": "is.cyan",
			"is-teal": "is.teal",
			"is-black": "is.black",
			"is-white": "is.white",
			"is-grey": "is.grey",
			"is-sepia": "is.sepia",
			"is-neon-green": "is.neon.green",
			"is-neon-orange": "is.neon.orange",
			"is-neon-blue": "is.neon.blue",
			"is-neon-yellow": "is.neon.yellow",
			"hover-body": "hover:body",
			"hover-main": "hover:main",
			"hover-sub": "hover:sub",
			"hover-txt": "hover:txt",
			"hover-light": "hover:light",
			"hover-dark": "hover:dark",
			"hover-primary": "hover:primary",
			"hover-secondary": "hover:secondary",
			"hover-warning": "hover:warning",
			"hover-error": "hover:error",
			"hover-danger": "hover:danger",
			"hover-info": "hover:info",
			"hover-success": "hover:success",
			"hover-red": "hover:red",
			"hover-amber": "hover:amber",
			"hover-orange": "hover:orange",
			"hover-yellow": "hover:yellow",
			"hover-lime": "hover:lime",
			"hover-green": "hover:green",
			"hover-sky": "hover:sky",
			"hover-blue": "hover:blue",
			"hover-indigo": "hover:indigo",
			"hover-violet": "hover:violet",
			"hover-pink": "hover:pink",
			"hover-purple": "hover:purple",
			"hover-cyan": "hover:cyan",
			"hover-teal": "hover:teal",
			"hover-black": "hover:black",
			"hover-white": "hover:white",
			"hover-grey": "hover:grey",
			"hover-sepia": "hover:sepia",
			"hover-neon-green": "hover:neon:green",
			"hover-neon-orange": "hover:neon:orange",
			"hover-neon-blue": "hover:neon:blue",
			"hover-neon-yellow": "hover:neon:yellow",
			"txt-body": "txt.body",
			"txt-main": "txt.main",
			"txt-sub": "txt.sub",
			"txt-txt": "txt.txt",
			"txt-light": "txt.light",
			"txt-dark": "txt.dark",
			"txt-primary": "txt.primary",
			"txt-secondary": "txt.secondary",
			"txt-warning": "txt.warning",
			"txt-error": "txt.error",
			"txt-danger": "txt.danger",
			"txt-info": "txt.info",
			"txt-success": "txt.success",
			"txt-red": "txt.red",
			"txt-amber": "txt.amber",
			"txt-orange": "txt.orange",
			"txt-yellow": "txt.yellow",
			"txt-lime": "txt.lime",
			"txt-green": "txt.green",
			"txt-sky": "txt.sky",
			"txt-blue": "txt.blue",
			"txt-indigo": "txt.indigo",
			"txt-violet": "txt.violet",
			"txt-pink": "txt.pink",
			"txt-purple": "txt.purple",
			"txt-cyan": "txt.cyan",
			"txt-teal": "txt.teal",
			"txt-black": "txt.black",
			"txt-white": "txt.white",
			"txt-grey": "txt.grey",
			"txt-sepia": "txt.sepia",
			"txt-neon-green": "txt.neon:green",
			"txt-neon-orange": "txt.neon:orange",
			"txt-neon-blue": "txt.neon:blue",
			"txt-neon-yellow": "txt.neon:yellow",
			"border-body": "border-body",
			"border-main": "border-main",
			"border-sub": "border-sub",
			"border-border": "border-border",
			"border-light": "border-light",
			"border-dark": "border-dark",
			"border-primary": "border-primary",
			"border-secondary": "border-secondary",
			"border-warning": "border-warning",
			"border-error": "border-error",
			"border-danger": "border-danger",
			"border-info": "border-info",
			"border-success": "border-success",
			"border-red": "border-red",
			"border-amber": "border-amber",
			"border-orange": "border-orange",
			"border-yellow": "border-yellow",
			"border-lime": "border-lime",
			"border-green": "border-green",
			"border-sky": "border-sky",
			"border-blue": "border-blue",
			"border-indigo": "border-indigo",
			"border-violet": "border-violet",
			"border-pink": "border-pink",
			"border-purple": "border-purple",
			"border-cyan": "border-cyan",
			"border-teal": "border-teal",
			"border-black": "border-black",
			"border-white": "border-white",
			"border-grey": "border-grey",
			"border-sepia": "border-sepia",
			"border-neon-green": "border-neon:green",
			"border-neon-orange": "border-neon:orange",
			"border-neon-blue": "border-neon:blue",
			"border-neon-yellow": "border-neon:yellow",
			"outline-body": "outline-body",
			"outline-main": "outline-main",
			"outline-sub": "outline-sub",
			"outline-outline": "outline-outline",
			"outline-light": "outline-light",
			"outline-dark": "outline-dark",
			"outline-primary": "outline-primary",
			"outline-secondary": "outline-secondary",
			"outline-warning": "outline-warning",
			"outline-error": "outline-error",
			"outline-danger": "outline-danger",
			"outline-info": "outline-info",
			"outline-success": "outline-success",
			"outline-red": "outline-red",
			"outline-amber": "outline-amber",
			"outline-orange": "outline-orange",
			"outline-yellow": "outline-yellow",
			"outline-lime": "outline-lime",
			"outline-green": "outline-green",
			"outline-sky": "outline-sky",
			"outline-blue": "outline-blue",
			"outline-indigo": "outline-indigo",
			"outline-violet": "outline-violet",
			"outline-pink": "outline-pink",
			"outline-purple": "outline-purple",
			"outline-cyan": "outline-cyan",
			"outline-teal": "outline-teal",
			"outline-black": "outline-black",
			"outline-white": "outline-white",
			"outline-grey": "outline-grey",
			"outline-sepia": "outline-sepia",
			"outline-neon-green": "outline-neon:green",
			"outline-neon-orange": "outline-neon:orange",
			"outline-neon-blue": "outline-neon:blue",
			"outline-neon-yellow": "outline-neon:yellow",
			
			"gap-0": "gap-0",
			"gap-1": "gap-1",
			"gap-2": "gap-2",
			"gap-3": "gap-3",
			"gap-4": "gap-4",
			"gap-5": "gap-5",
			"gap-6": "gap-6",
			"gap-7": "gap-7",
			"gap-8": "gap-8",
			"gap-9": "gap-9",
			"gap-10": "gap-10",
			
			"grid": "grid",
			"grid-1": "grid/1",
			"sm-grid-1": "sm:grid/1",
			"md-grid-1": "md:grid/1",
			"lg-grid-1": "lg:grid/1",
			"xl-grid-1": "xl:grid/1",
			"xxl-grid-1": "xxl:grid/1",
			"grid-2": "grid/2",
			"sm-grid-2": "sm:grid/2",
			"md-grid-2": "md:grid/2",
			"lg-grid-2": "lg:grid/2",
			"xl-grid-2": "xl:grid/2",
			"xxl-grid-2": "xxl:grid/2",
			"grid-3": "grid/3",
			"sm-grid-3": "sm:grid/3",
			"md-grid-3": "md:grid/3",
			"lg-grid-3": "lg:grid/3",
			"xl-grid-3": "xl:grid/3",
			"xxl-grid-3": "xxl:grid/3",
			"grid-4": "grid/4",
			"sm-grid-4": "sm:grid/4",
			"md-grid-4": "md:grid/4",
			"lg-grid-4": "lg:grid/4",
			"xl-grid-4": "xl:grid/4",
			"xxl-grid-4": "xxl:grid/4",
			"grid-5": "grid/5",
			"sm-grid-5": "sm:grid/5",
			"md-grid-5": "md:grid/5",
			"lg-grid-5": "lg:grid/5",
			"xl-grid-5": "xl:grid/5",
			"xxl-grid-5": "xxl:grid/5",
			"grid-6": "grid/6",
			"sm-grid-6": "sm:grid/6",
			"md-grid-6": "md:grid/6",
			"lg-grid-6": "lg:grid/6",
			"xl-grid-6": "xl:grid/6",
			"xxl-grid-6": "xxl:grid/6",
			"grid-7": "grid/7",
			"sm-grid-7": "sm:grid/7",
			"md-grid-7": "md:grid/7",
			"lg-grid-7": "lg:grid/7",
			"xl-grid-7": "xl:grid/7",
			"xxl-grid-7": "xxl:grid/7",
			"grid-8": "grid/8",
			"sm-grid-8": "sm:grid/8",
			"md-grid-8": "md:grid/8",
			"lg-grid-8": "lg:grid/8",
			"xl-grid-8": "xl:grid/8",
			"xxl-grid-8": "xxl:grid/8",
			"grid-9": "grid/9",
			"sm-grid-9": "sm:grid/9",
			"md-grid-9": "md:grid/9",
			"lg-grid-9": "lg:grid/9",
			"xl-grid-9": "xl:grid/9",
			"xxl-grid-9": "xxl:grid/9",
			"grid-10": "grid/10",
			"sm-grid-10": "sm:grid/10",
			"md-grid-10": "md:grid/10",
			"lg-grid-10": "lg:grid/10",
			"xl-grid-10": "xl:grid/10",
			"xxl-grid-10": "xxl:grid/10",
			"grid-11": "grid/11",
			"sm-grid-11": "sm:grid/11",
			"md-grid-11": "md:grid/11",
			"lg-grid-11": "lg:grid/11",
			"xl-grid-11": "xl:grid/11",
			"xxl-grid-11": "xxl:grid/11",
			"grid-12": "grid/12",
			"sm-grid-12": "sm:grid/12",
			"md-grid-12": "md:grid/12",
			"lg-grid-12": "lg:grid/12",
			"xl-grid-12": "xl:grid/12",
			"xxl-grid-12": "xxl:grid/12",

			"col": "col",
			"col-1": "col/1",
			"sm-col-1": "sm:col/1",
			"md-col-1": "md:col/1",
			"lg-col-1": "lg:col/1",
			"xl-col-1": "xl:col/1",
			"xxl-col-1": "xxl:col/1",
			"col-2": "col/2",
			"sm-col-2": "sm:col/2",
			"md-col-2": "md:col/2",
			"lg-col-2": "lg:col/2",
			"xl-col-2": "xl:col/2",
			"xxl-col-2": "xxl:col/2",
			"col-3": "col/3",
			"sm-col-3": "sm:col/3",
			"md-col-3": "md:col/3",
			"lg-col-3": "lg:col/3",
			"xl-col-3": "xl:col/3",
			"xxl-col-3": "xxl:col/3",
			"col-4": "col/4",
			"sm-col-4": "sm:col/4",
			"md-col-4": "md:col/4",
			"lg-col-4": "lg:col/4",
			"xl-col-4": "xl:col/4",
			"xxl-col-4": "xxl:col/4",
			"col-5": "col/5",
			"sm-col-5": "sm:col/5",
			"md-col-5": "md:col/5",
			"lg-col-5": "lg:col/5",
			"xl-col-5": "xl:col/5",
			"xxl-col-5": "xxl:col/5",
			"col-6": "col/6",
			"sm-col-6": "sm:col/6",
			"md-col-6": "md:col/6",
			"lg-col-6": "lg:col/6",
			"xl-col-6": "xl:col/6",
			"xxl-col-6": "xxl:col/6",
			"col-7": "col/7",
			"sm-col-7": "sm:col/7",
			"md-col-7": "md:col/7",
			"lg-col-7": "lg:col/7",
			"xl-col-7": "xl:col/7",
			"xxl-col-7": "xxl:col/7",
			"col-8": "col/8",
			"sm-col-8": "sm:col/8",
			"md-col-8": "md:col/8",
			"lg-col-8": "lg:col/8",
			"xl-col-8": "xl:col/8",
			"xxl-col-8": "xxl:col/8",
			"col-9": "col/9",
			"sm-col-9": "sm:col/9",
			"md-col-9": "md:col/9",
			"lg-col-9": "lg:col/9",
			"xl-col-9": "xl:col/9",
			"xxl-col-9": "xxl:col/9",
			"col-10": "col/10",
			"sm-col-10": "sm:col/10",
			"md-col-10": "md:col/10",
			"lg-col-10": "lg:col/10",
			"xl-col-10": "xl:col/10",
			"xxl-col-10": "xxl:col/10",
			"col-11": "col/11",
			"sm-col-11": "sm:col/11",
			"md-col-11": "md:col/11",
			"lg-col-11": "lg:col/11",
			"xl-col-11": "xl:col/11",
			"xxl-col-11": "xxl:col/11",
			"col-12": "col/12",
			"sm-col-12": "sm:col/12",
			"md-col-12": "md:col/12",
			"lg-col-12": "lg:col/12",
			"xl-col-12": "xl:col/12",
			"xxl-col-12": "xxl:col/12",
			
			"offset-0": "offset/0",
			"offset-1": "offset/1",
			"offset-2": "offset/2",
			"offset-3": "offset/3",
			"offset-4": "offset/4",
			"offset-5": "offset/5",
			"offset-6": "offset/6",
			"offset-7": "offset/7",
			"offset-8": "offset/8",
			"offset-9": "offset/9",
			"offset-10": "offset/10",
			"offset-11": "offset/11",
			"offset-12": "offset/12",						
			
			"z-index-0": "z.0",
			"z-index-2": "z.2",
			"z-navbar": "z.navbar",
			"z-back": "z.back",

			"height-25": "height-25",
			"height-25-vh": "height-25.vh",
			"height-25-px": "height-25.px",
			"height-50": "height-50",
			"height-50-vh": "height-50.vh",
			"height-50-px": "height-50.px",
			"height-75": "height-75",
			"height-75-vh": "height-75.vh",
			"height-75-px": "height-75.px",
			"height-100": "height-100",
			"height-100-vh": "height-100.vh",
			"height-100-px": "height-100.px",
			"height-150-px": "height-150.px",
			"height-175-px": "height-175.px",
			"height-200-px": "height-200.px",
			"height-250-px": "height-250.px",
			"height-275-px": "height-275.px",
			"height-300-px": "height-300.px",
			
			"width-25": "width-25",
			"width-25-vw": "width-25.vw",
			"width-25-px": "width-25.px",
			"width-50": "width-50",
			"width-50-vw": "width-50.vw",
			"width-50-px": "width-50.px",
			"width-75": "width-75",
			"width-75-vw": "width-75.vw",
			"width-75-px": "width-75.px",
			"width-100": "width-100",
			"width-100-vw": "width-100.vw",
			"width-100-px": "width-100.px",
			"width-150-px": "width-150.px",
			"width-175-px": "width-175.px",
			"width-200-px": "width-200.px",
			"width-250-px": "width-250.px",
			"width-275-px": "width-275.px",
			"width-300-px": "width-300.px",
			
			"container": "container",
			"full-container": "full:container",
			"sm-container": "sm:container",
			"md-container": "md:container",
			"lg-container": "lg:container",
			"xl-container": "xl:container",
			"xxl-container": "xxl:container",

			"float-left": "float-left",
			"float-right": "float-right",
			"float-none": "float-none",
			"float-start": "float-start",
			"float-end": "float-end",

			"clear-left": "clear-left",
			"clear-right": "clear-right",
			"clear-none": "clear-none",
			"clear-both": "clear-both",
			"clear-start": "clear-start",
			"clear-end": "clear-end",

			"invisible": "invisible",
			"visible": "visible",
			"ratio": "ratio",
			"ratio-1": "ratio-1",
			"ratio-square": "ratio-square",

			"bg-cover": "bg/cover",
			"bg-contain": "bg/contain",
			"bg-fixed": "bg/fixed",
			"bg-local": "bg/local",
			"bg-scroll": "bg/scroll",

			"flex": "flex",
			"display-flex": "display-flex",
			"flex-grow": "flex-grow",
			"flex-shrink": "flex-shrink",
			"flex-wrap": "flex-wrap",
			"flex-nowrap": "flex-nowrap",
			"flex-row": "flex-row",
			"flex-column": "flex-column",
			"flex-list": "flex-list",
			"flex-left": "flex-left",
			"flex-start": "flex-start",
			"flex-end": "flex-end",
			"flex-right": "flex-right",

			"display-grid": "display-grid",
			"display-none": "display-none",
			"display-block": "display-block",
			"display-inline": "display-inline",
			"display-inline-block": "display-inline/block",
			"display-inline-grid": "display-inline/grid",
			"display-inline-flex": "display-inline/flex",
			"display-flow-root": "display-flow/root",
			"display-block-flex": "display-block/flex",
			"display-block-flow": "display-block/flow",
			"display-block-grid": "display-block/grid",

			"display-table": "display-table",
			"table": "table",
			"table-row": "table/row",
			"display-list": "display-list/item",
			"display-inherit": "display-inherit",
			"display-initial": "display-initial",
			"display-revert": "display-revert",
			"display-unset": "display-unset",

			"align-center": "align-center",
			"align-between": "align-between",
			"align-around": "align-around",
			"align-evenly": "align-evenly",
			"items-start": "items-start",
			"items-end": "items-end",
			"items-center": "items-center",
			"items-baseline": "items-baseline",
			"items-stretch": "items-stretch",
			"content-start": "content-start",
			"content-end": "content-end",
			"content-center": "content-center",
			"content-between": "content-between",
			"content-around": "content-around",
			"content-stretch": "content-stretch",
			"self-auto": "self-auto",
			"self-start": "self-start",
			"self-end": "self-end",
			"self-center": "self-center",
			"self-baseline": "self-baseline",
			"self-stretch": "self-stretch",
			"order-first": "order-first",
			"order-0": "order-0",
			"order-1": "order-1",
			"order-2": "order-2",
			"order-3": "order-3",
			"order-4": "order-4",
			"order-5": "order-5",
			"order-6": "order-6",
			"order-7": "order-7",
			"order-last": "order-last",

			"sm-float-left": "sm:float-left",
			"sm-float-right": "sm:float-right",
			"sm-float-none": "sm:float-none",
			"sm-float-start": "sm:float-start",
			"sm-float-end": "sm:float-end",

			"sm-clear-left": "sm:clear-left",
			"sm-clear-right": "sm:clear-right",
			"sm-clear-none": "sm:clear-none",
			"sm-clear-both": "sm:clear-both",
			"sm-clear-start": "sm:clear-start",
			"sm-clear-end": "sm:clear-end",

			"sm-invisible": "sm:invisible",
			"sm-visible": "sm:visible",
			"sm-ratio": "sm:ratio",
			"sm-ratio-1": "sm:ratio-1",
			"sm-ratio-square": "sm:ratio-square",

			"sm-bg-cover": "sm:bg/cover",
			"sm-bg-contain": "sm:bg/contain",
			"sm-bg-fixed": "sm:bg/fixed",
			"sm-bg-local": "sm:bg/local",
			"sm-bg-scroll": "sm:bg/scroll",

			"sm-flex": "sm:flex",
			"sm-display-flex": "sm:display-flex",
			"sm-flex-grow": "sm:flex-grow",
			"sm-flex-shrink": "sm:flex-shrink",
			"sm-flex-wrap": "sm:flex-wrap",
			"sm-flex-nowrap": "sm:flex-nowrap",
			"sm-flex-row": "sm:flex-row",
			"sm-flex-column": "sm:flex-column",
			"sm-flex-list": "sm:flex-list",
			"sm-flex-left": "sm:flex-left",
			"sm-flex-start": "sm:flex-start",
			"sm-flex-end": "sm:flex-end",
			"sm-flex-right": "sm:flex-right",

			"sm-display-grid": "sm:display-grid",
			"sm-display-none": "sm:display-none",
			"sm-display-block": "sm:display-block",
			"sm-display-inline": "sm:display-inline",
			"sm-display-inline-block": "sm:display-inline/block",
			"sm-display-inline-grid": "sm:display-inline/grid",
			"sm-display-inline-flex": "sm:display-inline/flex",
			"sm-display-flow-root": "sm:display-flow/root",
			"sm-display-block-flex": "sm:display-block/flex",
			"sm-display-block-flow": "sm:display-block/flow",
			"sm-display-block-grid": "sm:display-block/grid",

			"sm-display-table": "sm:display-table",
			"sm-table": "sm:table",
			"sm-table-row": "sm:table/row",
			"sm-display-list": "sm:display-list/item",
			"sm-display-inherit": "sm:display-inherit",
			"sm-display-initial": "sm:display-initial",
			"sm-display-revert": "sm:display-revert",
			"sm-display-unset": "sm:display-unset",

			"sm-align-center": "sm:align-center",
			"sm-align-between": "sm:align-between",
			"sm-align-around": "sm:align-around",
			"sm-align-evenly": "sm:align-evenly",
			"sm-items-start": "sm:items-start",
			"sm-items-end": "sm:items-end",
			"sm-items-center": "sm:items-center",
			"sm-items-baseline": "sm:items-baseline",
			"sm-items-stretch": "sm:items-stretch",
			"sm-content-start": "sm:content-start",
			"sm-content-end": "sm:content-end",
			"sm-content-center": "sm:content-center",
			"sm-content-between": "sm:content-between",
			"sm-content-around": "sm:content-around",
			"sm-content-stretch": "sm:content-stretch",
			"sm-self-auto": "sm:self-auto",
			"sm-self-start": "sm:self-start",
			"sm-self-end": "sm:self-end",
			"sm-self-center": "sm:self-center",
			"sm-self-baseline": "sm:self-baseline",
			"sm-self-stretch": "sm:self-stretch",
			"sm-order-first": "sm:order-first",
			"sm-order-0": "sm:order-0",
			"sm-order-1": "sm:order-1",
			"sm-order-2": "sm:order-2",
			"sm-order-3": "sm:order-3",
			"sm-order-4": "sm:order-4",
			"sm-order-5": "sm:order-5",
			"sm-order-6": "sm:order-6",
			"sm-order-7": "sm:order-7",
			"sm-order-last": "sm:order-last",

			"md-float-left": "md:float-left",
			"md-float-right": "md:float-right",
			"md-float-none": "md:float-none",
			"md-float-start": "md:float-start",
			"md-float-end": "md:float-end",

			"md-clear-left": "md:clear-left",
			"md-clear-right": "md:clear-right",
			"md-clear-none": "md:clear-none",
			"md-clear-both": "md:clear-both",
			"md-clear-start": "md:clear-start",
			"md-clear-end": "md:clear-end",

			"md-invisible": "md:invisible",
			"md-visible": "md:visible",
			"md-ratio": "md:ratio",
			"md-ratio-1": "md:ratio-1",
			"md-ratio-square": "md:ratio-square",

			"md-bg-cover": "md:bg/cover",
			"md-bg-contain": "md:bg/contain",
			"md-bg-fixed": "md:bg/fixed",
			"md-bg-local": "md:bg/local",
			"md-bg-scroll": "md:bg/scroll",

			"md-flex": "md:flex",
			"md-display-flex": "md:display-flex",
			"md-flex-grow": "md:flex-grow",
			"md-flex-shrink": "md:flex-shrink",
			"md-flex-wrap": "md:flex-wrap",
			"md-flex-nowrap": "md:flex-nowrap",
			"md-flex-row": "md:flex-row",
			"md-flex-column": "md:flex-column",
			"md-flex-list": "md:flex-list",
			"md-flex-left": "md:flex-left",
			"md-flex-start": "md:flex-start",
			"md-flex-end": "md:flex-end",
			"md-flex-right": "md:flex-right",

			"md-display-grid": "md:display-grid",
			"md-display-none": "md:display-none",
			"md-display-block": "md:display-block",
			"md-display-inline": "md:display-inline",
			"md-display-inline-block": "md:display-inline/block",
			"md-display-inline-grid": "md:display-inline/grid",
			"md-display-inline-flex": "md:display-inline/flex",
			"md-display-flow-root": "md:display-flow/root",
			"md-display-block-flex": "md:display-block/flex",
			"md-display-block-flow": "md:display-block/flow",
			"md-display-block-grid": "md:display-block/grid",

			"md-display-table": "md:display-table",
			"md-table": "md:table",
			"md-table-row": "md:table/row",
			"md-display-list": "md:display-list/item",
			"md-display-inherit": "md:display-inherit",
			"md-display-initial": "md:display-initial",
			"md-display-revert": "md:display-revert",
			"md-display-unset": "md:display-unset",

			"md-align-center": "md:align-center",
			"md-align-between": "md:align-between",
			"md-align-around": "md:align-around",
			"md-align-evenly": "md:align-evenly",
			"md-items-start": "md:items-start",
			"md-items-end": "md:items-end",
			"md-items-center": "md:items-center",
			"md-items-baseline": "md:items-baseline",
			"md-items-stretch": "md:items-stretch",
			"md-content-start": "md:content-start",
			"md-content-end": "md:content-end",
			"md-content-center": "md:content-center",
			"md-content-between": "md:content-between",
			"md-content-around": "md:content-around",
			"md-content-stretch": "md:content-stretch",
			"md-self-auto": "md:self-auto",
			"md-self-start": "md:self-start",
			"md-self-end": "md:self-end",
			"md-self-center": "md:self-center",
			"md-self-baseline": "md:self-baseline",
			"md-self-stretch": "md:self-stretch",
			"md-order-first": "md:order-first",
			"md-order-0": "md:order-0",
			"md-order-1": "md:order-1",
			"md-order-2": "md:order-2",
			"md-order-3": "md:order-3",
			"md-order-4": "md:order-4",
			"md-order-5": "md:order-5",
			"md-order-6": "md:order-6",
			"md-order-7": "md:order-7",
			"md-order-last": "md:order-last",

			"lg-float-left": "lg:float-left",
			"lg-float-right": "lg:float-right",
			"lg-float-none": "lg:float-none",
			"lg-float-start": "lg:float-start",
			"lg-float-end": "lg:float-end",

			"lg-clear-left": "lg:clear-left",
			"lg-clear-right": "lg:clear-right",
			"lg-clear-none": "lg:clear-none",
			"lg-clear-both": "lg:clear-both",
			"lg-clear-start": "lg:clear-start",
			"lg-clear-end": "lg:clear-end",

			"lg-invisible": "lg:invisible",
			"lg-visible": "lg:visible",
			"lg-ratio": "lg:ratio",
			"lg-ratio-1": "lg:ratio-1",
			"lg-ratio-square": "lg:ratio-square",

			"lg-bg-cover": "lg:bg/cover",
			"lg-bg-contain": "lg:bg/contain",
			"lg-bg-fixed": "lg:bg/fixed",
			"lg-bg-local": "lg:bg/local",
			"lg-bg-scroll": "lg:bg/scroll",

			"lg-flex": "lg:flex",
			"lg-display-flex": "lg:display-flex",
			"lg-flex-grow": "lg:flex-grow",
			"lg-flex-shrink": "lg:flex-shrink",
			"lg-flex-wrap": "lg:flex-wrap",
			"lg-flex-nowrap": "lg:flex-nowrap",
			"lg-flex-row": "lg:flex-row",
			"lg-flex-column": "lg:flex-column",
			"lg-flex-list": "lg:flex-list",
			"lg-flex-left": "lg:flex-left",
			"lg-flex-start": "lg:flex-start",
			"lg-flex-end": "lg:flex-end",
			"lg-flex-right": "lg:flex-right",

			"lg-display-grid": "lg:display-grid",
			"lg-display-none": "lg:display-none",
			"lg-display-block": "lg:display-block",
			"lg-display-inline": "lg:display-inline",
			"lg-display-inline-block": "lg:display-inline/block",
			"lg-display-inline-grid": "lg:display-inline/grid",
			"lg-display-inline-flex": "lg:display-inline/flex",
			"lg-display-flow-root": "lg:display-flow/root",
			"lg-display-block-flex": "lg:display-block/flex",
			"lg-display-block-flow": "lg:display-block/flow",
			"lg-display-block-grid": "lg:display-block/grid",

			"lg-display-table": "lg:display-table",
			"lg-table": "lg:table",
			"lg-table-row": "lg:table/row",
			"lg-display-list": "lg:display-list/item",
			"lg-display-inherit": "lg:display-inherit",
			"lg-display-initial": "lg:display-initial",
			"lg-display-revert": "lg:display-revert",
			"lg-display-unset": "lg:display-unset",

			"lg-align-center": "lg:align-center",
			"lg-align-between": "lg:align-between",
			"lg-align-around": "lg:align-around",
			"lg-align-evenly": "lg:align-evenly",
			"lg-items-start": "lg:items-start",
			"lg-items-end": "lg:items-end",
			"lg-items-center": "lg:items-center",
			"lg-items-baseline": "lg:items-baseline",
			"lg-items-stretch": "lg:items-stretch",
			"lg-content-start": "lg:content-start",
			"lg-content-end": "lg:content-end",
			"lg-content-center": "lg:content-center",
			"lg-content-between": "lg:content-between",
			"lg-content-around": "lg:content-around",
			"lg-content-stretch": "lg:content-stretch",
			"lg-self-auto": "lg:self-auto",
			"lg-self-start": "lg:self-start",
			"lg-self-end": "lg:self-end",
			"lg-self-center": "lg:self-center",
			"lg-self-baseline": "lg:self-baseline",
			"lg-self-stretch": "lg:self-stretch",
			"lg-order-first": "lg:order-first",
			"lg-order-0": "lg:order-0",
			"lg-order-1": "lg:order-1",
			"lg-order-2": "lg:order-2",
			"lg-order-3": "lg:order-3",
			"lg-order-4": "lg:order-4",
			"lg-order-5": "lg:order-5",
			"lg-order-6": "lg:order-6",
			"lg-order-7": "lg:order-7",
			"lg-order-last": "lg:order-last",

			"xl-float-left": "xl:float-left",
			"xl-float-right": "xl:float-right",
			"xl-float-none": "xl:float-none",
			"xl-float-start": "xl:float-start",
			"xl-float-end": "xl:float-end",

			"xl-clear-left": "xl:clear-left",
			"xl-clear-right": "xl:clear-right",
			"xl-clear-none": "xl:clear-none",
			"xl-clear-both": "xl:clear-both",
			"xl-clear-start": "xl:clear-start",
			"xl-clear-end": "xl:clear-end",

			"xl-invisible": "xl:invisible",
			"xl-visible": "xl:visible",
			"xl-ratio": "xl:ratio",
			"xl-ratio-1": "xl:ratio-1",
			"xl-ratio-square": "xl:ratio-square",

			"xl-bg-cover": "xl:bg/cover",
			"xl-bg-contain": "xl:bg/contain",
			"xl-bg-fixed": "xl:bg/fixed",
			"xl-bg-local": "xl:bg/local",
			"xl-bg-scroll": "xl:bg/scroll",

			"xl-flex": "xl:flex",
			"xl-display-flex": "xl:display-flex",
			"xl-flex-grow": "xl:flex-grow",
			"xl-flex-shrink": "xl:flex-shrink",
			"xl-flex-wrap": "xl:flex-wrap",
			"xl-flex-nowrap": "xl:flex-nowrap",
			"xl-flex-row": "xl:flex-row",
			"xl-flex-column": "xl:flex-column",
			"xl-flex-list": "xl:flex-list",
			"xl-flex-left": "xl:flex-left",
			"xl-flex-start": "xl:flex-start",
			"xl-flex-end": "xl:flex-end",
			"xl-flex-right": "xl:flex-right",

			"xl-display-grid": "xl:display-grid",
			"xl-display-none": "xl:display-none",
			"xl-display-block": "xl:display-block",
			"xl-display-inline": "xl:display-inline",
			"xl-display-inline-block": "xl:display-inline/block",
			"xl-display-inline-grid": "xl:display-inline/grid",
			"xl-display-inline-flex": "xl:display-inline/flex",
			"xl-display-flow-root": "xl:display-flow/root",
			"xl-display-block-flex": "xl:display-block/flex",
			"xl-display-block-flow": "xl:display-block/flow",
			"xl-display-block-grid": "xl:display-block/grid",

			"xl-display-table": "xl:display-table",
			"xl-table": "xl:table",
			"xl-table-row": "xl:table/row",
			"xl-display-list": "xl:display-list/item",
			"xl-display-inherit": "xl:display-inherit",
			"xl-display-initial": "xl:display-initial",
			"xl-display-revert": "xl:display-revert",
			"xl-display-unset": "xl:display-unset",

			"xl-align-center": "xl:align-center",
			"xl-align-between": "xl:align-between",
			"xl-align-around": "xl:align-around",
			"xl-align-evenly": "xl:align-evenly",
			"xl-items-start": "xl:items-start",
			"xl-items-end": "xl:items-end",
			"xl-items-center": "xl:items-center",
			"xl-items-baseline": "xl:items-baseline",
			"xl-items-stretch": "xl:items-stretch",
			"xl-content-start": "xl:content-start",
			"xl-content-end": "xl:content-end",
			"xl-content-center": "xl:content-center",
			"xl-content-between": "xl:content-between",
			"xl-content-around": "xl:content-around",
			"xl-content-stretch": "xl:content-stretch",
			"xl-self-auto": "xl:self-auto",
			"xl-self-start": "xl:self-start",
			"xl-self-end": "xl:self-end",
			"xl-self-center": "xl:self-center",
			"xl-self-baseline": "xl:self-baseline",
			"xl-self-stretch": "xl:self-stretch",
			"xl-order-first": "xl:order-first",
			"xl-order-0": "xl:order-0",
			"xl-order-1": "xl:order-1",
			"xl-order-2": "xl:order-2",
			"xl-order-3": "xl:order-3",
			"xl-order-4": "xl:order-4",
			"xl-order-5": "xl:order-5",
			"xl-order-6": "xl:order-6",
			"xl-order-7": "xl:order-7",
			"xl-order-last": "xl:order-last",

			"xxl-float-left": "xxl:float-left",
			"xxl-float-right": "xxl:float-right",
			"xxl-float-none": "xxl:float-none",
			"xxl-float-start": "xxl:float-start",
			"xxl-float-end": "xxl:float-end",

			"xxl-clear-left": "xxl:clear-left",
			"xxl-clear-right": "xxl:clear-right",
			"xxl-clear-none": "xxl:clear-none",
			"xxl-clear-both": "xxl:clear-both",
			"xxl-clear-start": "xxl:clear-start",
			"xxl-clear-end": "xxl:clear-end",

			"xxl-invisible": "xxl:invisible",
			"xxl-visible": "xxl:visible",
			"xxl-ratio": "xxl:ratio",
			"xxl-ratio-1": "xxl:ratio-1",
			"xxl-ratio-square": "xxl:ratio-square",

			"xxl-bg-cover": "xxl:bg/cover",
			"xxl-bg-contain": "xxl:bg/contain",
			"xxl-bg-fixed": "xxl:bg/fixed",
			"xxl-bg-local": "xxl:bg/local",
			"xxl-bg-scroll": "xxl:bg/scroll",

			"xxl-flex": "xxl:flex",
			"xxl-display-flex": "xxl:display-flex",
			"xxl-flex-grow": "xxl:flex-grow",
			"xxl-flex-shrink": "xxl:flex-shrink",
			"xxl-flex-wrap": "xxl:flex-wrap",
			"xxl-flex-nowrap": "xxl:flex-nowrap",
			"xxl-flex-row": "xxl:flex-row",
			"xxl-flex-column": "xxl:flex-column",
			"xxl-flex-list": "xxl:flex-list",
			"xxl-flex-left": "xxl:flex-left",
			"xxl-flex-start": "xxl:flex-start",
			"xxl-flex-end": "xxl:flex-end",
			"xxl-flex-right": "xxl:flex-right",

			"xxl-display-grid": "xxl:display-grid",
			"xxl-display-none": "xxl:display-none",
			"xxl-display-block": "xxl:display-block",
			"xxl-display-inline": "xxl:display-inline",
			"xxl-display-inline-block": "xxl:display-inline/block",
			"xxl-display-inline-grid": "xxl:display-inline/grid",
			"xxl-display-inline-flex": "xxl:display-inline/flex",
			"xxl-display-flow-root": "xxl:display-flow/root",
			"xxl-display-block-flex": "xxl:display-block/flex",
			"xxl-display-block-flow": "xxl:display-block/flow",
			"xxl-display-block-grid": "xxl:display-block/grid",

			"xxl-display-table": "xxl:display-table",
			"xxl-table": "xxl:table",
			"xxl-table-row": "xxl:table/row",
			"xxl-display-list": "xxl:display-list/item",
			"xxl-display-inherit": "xxl:display-inherit",
			"xxl-display-initial": "xxl:display-initial",
			"xxl-display-revert": "xxl:display-revert",
			"xxl-display-unset": "xxl:display-unset",

			"xxl-align-center": "xxl:align-center",
			"xxl-align-between": "xxl:align-between",
			"xxl-align-around": "xxl:align-around",
			"xxl-align-evenly": "xxl:align-evenly",
			"xxl-items-start": "xxl:items-start",
			"xxl-items-end": "xxl:items-end",
			"xxl-items-center": "xxl:items-center",
			"xxl-items-baseline": "xxl:items-baseline",
			"xxl-items-stretch": "xxl:items-stretch",
			"xxl-content-start": "xxl:content-start",
			"xxl-content-end": "xxl:content-end",
			"xxl-content-center": "xxl:content-center",
			"xxl-content-between": "xxl:content-between",
			"xxl-content-around": "xxl:content-around",
			"xxl-content-stretch": "xxl:content-stretch",
			"xxl-self-auto": "xxl:self-auto",
			"xxl-self-start": "xxl:self-start",
			"xxl-self-end": "xxl:self-end",
			"xxl-self-center": "xxl:self-center",
			"xxl-self-baseline": "xxl:self-baseline",
			"xxl-self-stretch": "xxl:self-stretch",
			"xxl-order-first": "xxl:order-first",
			"xxl-order-0": "xxl:order-0",
			"xxl-order-1": "xxl:order-1",
			"xxl-order-2": "xxl:order-2",
			"xxl-order-3": "xxl:order-3",
			"xxl-order-4": "xxl:order-4",
			"xxl-order-5": "xxl:order-5",
			"xxl-order-6": "xxl:order-6",
			"xxl-order-7": "xxl:order-7",
			"xxl-order-last": "xxl:order-last",

			"mx-auto": "mx-auto",
			"m-0": "m-0",
			"ml-0": "ml-0",
			"mr-0": "mr-0",
			"mt-0": "mt-0",
			"mb-0": "mb-0",
			"my-0": "my-0",
			"mx-0": "mx-0",
			"m-1": "m-1",
			"ml-1": "ml-1",
			"mr-1": "mr-1",
			"mt-1": "mt-1",
			"mb-1": "mb-1",
			"my-1": "my-1",
			"mx-1": "mx-1",
			"m-2": "m-2",
			"ml-2": "ml-2",
			"mr-2": "mr-2",
			"mt-2": "mt-2",
			"mb-2": "mb-2",
			"my-2": "my-2",
			"mx-2": "mx-2",
			"m-3": "m-3",
			"ml-3": "ml-3",
			"mr-3": "mr-3",
			"mt-3": "mt-3",
			"mb-3": "mb-3",
			"my-3": "my-3",
			"mx-3": "mx-3",
			"m-4": "m-4",
			"ml-4": "ml-4",
			"mr-4": "mr-4",
			"mt-4": "mt-4",
			"mb-4": "mb-4",
			"my-4": "my-4",
			"mx-4": "mx-4",
			"m-5": "m-5",
			"ml-5": "ml-5",
			"mr-5": "mr-5",
			"mt-5": "mt-5",
			"mb-5": "mb-5",
			"my-5": "my-5",
			"mx-5": "mx-5",
			"m-6": "m-6",
			"ml-6": "ml-6",
			"mr-6": "mr-6",
			"mt-6": "mt-6",
			"mb-6": "mb-6",
			"my-6": "my-6",
			"mx-6": "mx-6",

			"sm-mx-auto": "sm:mx-auto",
			"sm-m-0": "sm:m-0",
			"sm-ml-0": "sm:ml-0",
			"sm-mr-0": "sm:mr-0",
			"sm-mt-0": "sm:mt-0",
			"sm-mb-0": "sm:mb-0",
			"sm-my-0": "sm:my-0",
			"sm-mx-0": "sm:mx-0",
			"sm-m-1": "sm:m-1",
			"sm-ml-1": "sm:ml-1",
			"sm-mr-1": "sm:mr-1",
			"sm-mt-1": "sm:mt-1",
			"sm-mb-1": "sm:mb-1",
			"sm-my-1": "sm:my-1",
			"sm-mx-1": "sm:mx-1",
			"sm-m-2": "sm:m-2",
			"sm-ml-2": "sm:ml-2",
			"sm-mr-2": "sm:mr-2",
			"sm-mt-2": "sm:mt-2",
			"sm-mb-2": "sm:mb-2",
			"sm-my-2": "sm:my-2",
			"sm-mx-2": "sm:mx-2",
			"sm-m-3": "sm:m-3",
			"sm-ml-3": "sm:ml-3",
			"sm-mr-3": "sm:mr-3",
			"sm-mt-3": "sm:mt-3",
			"sm-mb-3": "sm:mb-3",
			"sm-my-3": "sm:my-3",
			"sm-mx-3": "sm:mx-3",
			"sm-m-4": "sm:m-4",
			"sm-ml-4": "sm:ml-4",
			"sm-mr-4": "sm:mr-4",
			"sm-mt-4": "sm:mt-4",
			"sm-mb-4": "sm:mb-4",
			"sm-my-4": "sm:my-4",
			"sm-mx-4": "sm:mx-4",
			"sm-m-5": "sm:m-5",
			"sm-ml-5": "sm:ml-5",
			"sm-mr-5": "sm:mr-5",
			"sm-mt-5": "sm:mt-5",
			"sm-mb-5": "sm:mb-5",
			"sm-my-5": "sm:my-5",
			"sm-mx-5": "sm:mx-5",
			"sm-m-6": "sm:m-6",
			"sm-ml-6": "sm:ml-6",
			"sm-mr-6": "sm:mr-6",
			"sm-mt-6": "sm:mt-6",
			"sm-mb-6": "sm:mb-6",
			"sm-my-6": "sm:my-6",
			"sm-mx-6": "sm:mx-6",

			"md-mx-auto": "md:mx-auto",
			"md-m-0": "md:m-0",
			"md-ml-0": "md:ml-0",
			"md-mr-0": "md:mr-0",
			"md-mt-0": "md:mt-0",
			"md-mb-0": "md:mb-0",
			"md-my-0": "md:my-0",
			"md-mx-0": "md:mx-0",
			"md-m-1": "md:m-1",
			"md-ml-1": "md:ml-1",
			"md-mr-1": "md:mr-1",
			"md-mt-1": "md:mt-1",
			"md-mb-1": "md:mb-1",
			"md-my-1": "md:my-1",
			"md-mx-1": "md:mx-1",
			"md-m-2": "md:m-2",
			"md-ml-2": "md:ml-2",
			"md-mr-2": "md:mr-2",
			"md-mt-2": "md:mt-2",
			"md-mb-2": "md:mb-2",
			"md-my-2": "md:my-2",
			"md-mx-2": "md:mx-2",
			"md-m-3": "md:m-3",
			"md-ml-3": "md:ml-3",
			"md-mr-3": "md:mr-3",
			"md-mt-3": "md:mt-3",
			"md-mb-3": "md:mb-3",
			"md-my-3": "md:my-3",
			"md-mx-3": "md:mx-3",
			"md-m-4": "md:m-4",
			"md-ml-4": "md:ml-4",
			"md-mr-4": "md:mr-4",
			"md-mt-4": "md:mt-4",
			"md-mb-4": "md:mb-4",
			"md-my-4": "md:my-4",
			"md-mx-4": "md:mx-4",
			"md-m-5": "md:m-5",
			"md-ml-5": "md:ml-5",
			"md-mr-5": "md:mr-5",
			"md-mt-5": "md:mt-5",
			"md-mb-5": "md:mb-5",
			"md-my-5": "md:my-5",
			"md-mx-5": "md:mx-5",
			"md-m-6": "md:m-6",
			"md-ml-6": "md:ml-6",
			"md-mr-6": "md:mr-6",
			"md-mt-6": "md:mt-6",
			"md-mb-6": "md:mb-6",
			"md-my-6": "md:my-6",
			"md-mx-6": "md:mx-6",

			"lg-mx-auto": "lg:mx-auto",
			"lg-m-0": "lg:m-0",
			"lg-ml-0": "lg:ml-0",
			"lg-mr-0": "lg:mr-0",
			"lg-mt-0": "lg:mt-0",
			"lg-mb-0": "lg:mb-0",
			"lg-my-0": "lg:my-0",
			"lg-mx-0": "lg:mx-0",
			"lg-m-1": "lg:m-1",
			"lg-ml-1": "lg:ml-1",
			"lg-mr-1": "lg:mr-1",
			"lg-mt-1": "lg:mt-1",
			"lg-mb-1": "lg:mb-1",
			"lg-my-1": "lg:my-1",
			"lg-mx-1": "lg:mx-1",
			"lg-m-2": "lg:m-2",
			"lg-ml-2": "lg:ml-2",
			"lg-mr-2": "lg:mr-2",
			"lg-mt-2": "lg:mt-2",
			"lg-mb-2": "lg:mb-2",
			"lg-my-2": "lg:my-2",
			"lg-mx-2": "lg:mx-2",
			"lg-m-3": "lg:m-3",
			"lg-ml-3": "lg:ml-3",
			"lg-mr-3": "lg:mr-3",
			"lg-mt-3": "lg:mt-3",
			"lg-mb-3": "lg:mb-3",
			"lg-my-3": "lg:my-3",
			"lg-mx-3": "lg:mx-3",
			"lg-m-4": "lg:m-4",
			"lg-ml-4": "lg:ml-4",
			"lg-mr-4": "lg:mr-4",
			"lg-mt-4": "lg:mt-4",
			"lg-mb-4": "lg:mb-4",
			"lg-my-4": "lg:my-4",
			"lg-mx-4": "lg:mx-4",
			"lg-m-5": "lg:m-5",
			"lg-ml-5": "lg:ml-5",
			"lg-mr-5": "lg:mr-5",
			"lg-mt-5": "lg:mt-5",
			"lg-mb-5": "lg:mb-5",
			"lg-my-5": "lg:my-5",
			"lg-mx-5": "lg:mx-5",
			"lg-m-6": "lg:m-6",
			"lg-ml-6": "lg:ml-6",
			"lg-mr-6": "lg:mr-6",
			"lg-mt-6": "lg:mt-6",
			"lg-mb-6": "lg:mb-6",
			"lg-my-6": "lg:my-6",
			"lg-mx-6": "lg:mx-6",

			"xl-mx-auto": "xl:mx-auto",
			"xl-m-0": "xl:m-0",
			"xl-ml-0": "xl:ml-0",
			"xl-mr-0": "xl:mr-0",
			"xl-mt-0": "xl:mt-0",
			"xl-mb-0": "xl:mb-0",
			"xl-my-0": "xl:my-0",
			"xl-mx-0": "xl:mx-0",
			"xl-m-1": "xl:m-1",
			"xl-ml-1": "xl:ml-1",
			"xl-mr-1": "xl:mr-1",
			"xl-mt-1": "xl:mt-1",
			"xl-mb-1": "xl:mb-1",
			"xl-my-1": "xl:my-1",
			"xl-mx-1": "xl:mx-1",
			"xl-m-2": "xl:m-2",
			"xl-ml-2": "xl:ml-2",
			"xl-mr-2": "xl:mr-2",
			"xl-mt-2": "xl:mt-2",
			"xl-mb-2": "xl:mb-2",
			"xl-my-2": "xl:my-2",
			"xl-mx-2": "xl:mx-2",
			"xl-m-3": "xl:m-3",
			"xl-ml-3": "xl:ml-3",
			"xl-mr-3": "xl:mr-3",
			"xl-mt-3": "xl:mt-3",
			"xl-mb-3": "xl:mb-3",
			"xl-my-3": "xl:my-3",
			"xl-mx-3": "xl:mx-3",
			"xl-m-4": "xl:m-4",
			"xl-ml-4": "xl:ml-4",
			"xl-mr-4": "xl:mr-4",
			"xl-mt-4": "xl:mt-4",
			"xl-mb-4": "xl:mb-4",
			"xl-my-4": "xl:my-4",
			"xl-mx-4": "xl:mx-4",
			"xl-m-5": "xl:m-5",
			"xl-ml-5": "xl:ml-5",
			"xl-mr-5": "xl:mr-5",
			"xl-mt-5": "xl:mt-5",
			"xl-mb-5": "xl:mb-5",
			"xl-my-5": "xl:my-5",
			"xl-mx-5": "xl:mx-5",
			"xl-m-6": "xl:m-6",
			"xl-ml-6": "xl:ml-6",
			"xl-mr-6": "xl:mr-6",
			"xl-mt-6": "xl:mt-6",
			"xl-mb-6": "xl:mb-6",
			"xl-my-6": "xl:my-6",
			"xl-mx-6": "xl:mx-6",

			"xxl-mx-auto": "xxl:mx-auto",
			"xxl-m-0": "xxl:m-0",
			"xxl-ml-0": "xxl:ml-0",
			"xxl-mr-0": "xxl:mr-0",
			"xxl-mt-0": "xxl:mt-0",
			"xxl-mb-0": "xxl:mb-0",
			"xxl-my-0": "xxl:my-0",
			"xxl-mx-0": "xxl:mx-0",
			"xxl-m-1": "xxl:m-1",
			"xxl-ml-1": "xxl:ml-1",
			"xxl-mr-1": "xxl:mr-1",
			"xxl-mt-1": "xxl:mt-1",
			"xxl-mb-1": "xxl:mb-1",
			"xxl-my-1": "xxl:my-1",
			"xxl-mx-1": "xxl:mx-1",
			"xxl-m-2": "xxl:m-2",
			"xxl-ml-2": "xxl:ml-2",
			"xxl-mr-2": "xxl:mr-2",
			"xxl-mt-2": "xxl:mt-2",
			"xxl-mb-2": "xxl:mb-2",
			"xxl-my-2": "xxl:my-2",
			"xxl-mx-2": "xxl:mx-2",
			"xxl-m-3": "xxl:m-3",
			"xxl-ml-3": "xxl:ml-3",
			"xxl-mr-3": "xxl:mr-3",
			"xxl-mt-3": "xxl:mt-3",
			"xxl-mb-3": "xxl:mb-3",
			"xxl-my-3": "xxl:my-3",
			"xxl-mx-3": "xxl:mx-3",
			"xxl-m-4": "xxl:m-4",
			"xxl-ml-4": "xxl:ml-4",
			"xxl-mr-4": "xxl:mr-4",
			"xxl-mt-4": "xxl:mt-4",
			"xxl-mb-4": "xxl:mb-4",
			"xxl-my-4": "xxl:my-4",
			"xxl-mx-4": "xxl:mx-4",
			"xxl-m-5": "xxl:m-5",
			"xxl-ml-5": "xxl:ml-5",
			"xxl-mr-5": "xxl:mr-5",
			"xxl-mt-5": "xxl:mt-5",
			"xxl-mb-5": "xxl:mb-5",
			"xxl-my-5": "xxl:my-5",
			"xxl-mx-5": "xxl:mx-5",
			"xxl-m-6": "xxl:m-6",
			"xxl-ml-6": "xxl:ml-6",
			"xxl-mr-6": "xxl:mr-6",
			"xxl-mt-6": "xxl:mt-6",
			"xxl-mb-6": "xxl:mb-6",
			"xxl-my-6": "xxl:my-6",
			"xxl-mx-6": "xxl:mx-6",
			"sticky-top": "sticky:top",
			"sticky-bottom": "sticky:bottom",
		},
        html: {
				"?version": "?v=<?= time(); ?>",
				"?v": "?v=<?= time(); ?>",
				"template": "<!DOCTYPE HTML>\n\
<html lang=\"en\">\n\
<head>\n\
\t<!-- Copyright 2016/"+year+" © Powered by Madw3b.Engine | https://madw3b.nl |  created at "+currentDate+" -->\n\
\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=2,shrink-to-fit=no\"/>\n\
\t<link rel=\"shortcut icon\" href=\"data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAh5JREFUOE+t009Ik2EcwPHv+77jXTrYltaYKbP8G9ND082D0cGgwzoYeK6DUBEdOkUQFEk1COnvwVuQGJ0kIoK6ePRdiRLqkmGzaWnZ3IZsa9P9e9/YUmMktUPP5XkOv9+H5/f7PY/Ar2UCnFvncrcJ4IewFd3d4j6nGCy2spLjXwN8GhtpB+Z2AOfZQcVcby8LiHycYvrpwP8DdMCV6uZOT4XZAqKEKEmIOplalxstn+P75Gv2x1YRMxukRR3L6QzhxQ+XgKFCCZ3AZNeFB0I+mybsf4el7SiaqvL+yVVE4L7LxWoqRSAep1qvJ5nL8SwY1IDW7R7c7Lk2en3+zWNs3b0sv33F4d6LfHvYj4yGp6OD2zMznGlsZDwUQi9JDC8sXAbubQN9rvN3n3/xviQ0N07NkePUudz0eIdJ5fPYTSYe+f0EYjH66utpMhq54/OdAMZ2plB7qE3RHWjhs/KCuq6TVIUXuXHQSk7TGPL7SasqE+Ew/U1NTEWj+NbXS6dwy+FQEtkssWwWa0UFjqoqdGKhA5Ap9CMaJby5yV5ZRhIEPLOzpcCg06nYzea/voMCsJJMktc0Bqan/wREQSCrqjQbjeyRpCKWyuWYj8Xwrq0Vb3TKZisiuwI1lZWMBAIsJpOomoYsiphkmXazmWNWK/v0+iI6FYnsDvyrhO36dgVONzQotQZDWX8hmEgwurRU0oNCZmtZ2b+D/MDGT8vB5DggBrzFAAAAAElFTkSuQmCC\">\n\
\t<title property=\"schema:name\">Madw3bTemplate<\/title>\n\
\t<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\n\
\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/>\n\
\t<meta name=\"referrer\" content=\"origin-when-cross-origin\"/>\n\
\t<meta name=\"country\" content=\"en\"/>\n\
\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=2,shrink-to-fit=no\"/>\n\
\t<meta property=\"schema:description\" name=\"description\" content=\"Examples and usage guidelines for form control styles, layout options, and custom components for creating a wide variety of form\"/>\n\
</head>\n\
<body class=\"no-transition\">\n\
\t<main>\n\
	\t\t\n\
\t</main>\n\
\t<!-- Copyright 2016/"+year+" © Powered by Madw3b.Engine | https://madw3b.nl | created at "+currentDate+" -->\n\
</body>\n\
</html>\n",

				"frameworktemplate": "<!DOCTYPE HTML>\n\
<html lang=\"en\">\n\
<head>\n\
\t<!-- Copyright 2016/"+year+" © Powered by Madw3b.Engine | https://madw3b.nl |  created at "+currentDate+" -->\n\
\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=2,shrink-to-fit=no\"/>\n\
\t<link rel=\"shortcut icon\" href=\"data:image/x-icon;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAh5JREFUOE+t009Ik2EcwPHv+77jXTrYltaYKbP8G9ND082D0cGgwzoYeK6DUBEdOkUQFEk1COnvwVuQGJ0kIoK6ePRdiRLqkmGzaWnZ3IZsa9P9e9/YUmMktUPP5XkOv9+H5/f7PY/Ar2UCnFvncrcJ4IewFd3d4j6nGCy2spLjXwN8GhtpB+Z2AOfZQcVcby8LiHycYvrpwP8DdMCV6uZOT4XZAqKEKEmIOplalxstn+P75Gv2x1YRMxukRR3L6QzhxQ+XgKFCCZ3AZNeFB0I+mybsf4el7SiaqvL+yVVE4L7LxWoqRSAep1qvJ5nL8SwY1IDW7R7c7Lk2en3+zWNs3b0sv33F4d6LfHvYj4yGp6OD2zMznGlsZDwUQi9JDC8sXAbubQN9rvN3n3/xviQ0N07NkePUudz0eIdJ5fPYTSYe+f0EYjH66utpMhq54/OdAMZ2plB7qE3RHWjhs/KCuq6TVIUXuXHQSk7TGPL7SasqE+Ew/U1NTEWj+NbXS6dwy+FQEtkssWwWa0UFjqoqdGKhA5Ap9CMaJby5yV5ZRhIEPLOzpcCg06nYzea/voMCsJJMktc0Bqan/wREQSCrqjQbjeyRpCKWyuWYj8Xwrq0Vb3TKZisiuwI1lZWMBAIsJpOomoYsiphkmXazmWNWK/v0+iI6FYnsDvyrhO36dgVONzQotQZDWX8hmEgwurRU0oNCZmtZ2b+D/MDGT8vB5DggBrzFAAAAAElFTkSuQmCC\">\n\
\t<title property=\"schema:name\">Madw3bTemplate<\/title>\n\
\t<meta http-equiv=\"cache-control\" content=\"no-cache\"/>\n\
\t<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/>\n\
\t<meta name=\"referrer\" content=\"origin-when-cross-origin\"/>\n\
\t<meta name=\"country\" content=\"en\"/>\n\
\t<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=2,shrink-to-fit=no\"/>\n\
\t<meta property=\"schema:description\" name=\"description\" content=\"Examples and usage guidelines for form control styles, layout options, and custom components for creating a wide variety of form\"/>\n\
\t<link href=\"../../scss/css/mad-framework.css\" rel=\"stylesheet\">\n\
\t<link href=\"style.css?<?= time(); ?>\" rel=\"stylesheet\">\n\
</head>\n\
<body class=\"no-transition\">\n\
\t<main>\n\
	\t\t\n\
\t</main>\n\
\t<!-- Copyright 2016/"+year+" © Powered by Madw3b.Engine | https://madw3b.nl | created at "+currentDate+" -->\n\
\t<script src=\"../../scss/js/framework.js\"></script>\n\
\t<script src=\"../../scss/js/localstorage.js\"></script>\n\
</body>\n\
</html>\n",

				"main-header": "<main-header>#focus</main-header>\n",		
				"heros-lider": "\t\t<hero-slider class=\"dotss controlls\" hero-overlay=\"1\" hero-effect=\"zoom\" hero-timing=\"8\">\n\
\t\t\t<div class=\"slides\">\n\
\t\t\t\t<item-slide class=\"slide active\" style=\"background-image: url('img/bg.jpg')\">\n\
\t\t\t\t\t<slide-text class=\"slide-text is.black\">\n\
\t\t\t\t\t\t<h3>Welcome to Our Website</h3>\n\
\t\t\t\t\t\t<p>Experience the best services with us</p>\n\
\t\t\t\t\t</slide-text>\n\
\t\t\t\t</item-slide>\n\
\n\
\t\t\t\t<item-slide class=\"slide\" style=\"background-image: url('img/wp12459723.webp')\">\n\
\t\t\t\t\t<slide-text class=\"slide-text is.black\">\n\
\t\t\t\t\t\t<h3>1Welcome to Our Website</h3>\n\
\t\t\t\t\t\t<p>1Experience the best services with us</p>\n\
\t\t\t\t\t</slide-text>\n\
\t\t\t\t</item-slide>\n\
\n\
\t\t\t\t<item-slide class=\"slide\" style=\"background-image: url('img/download.jpg')\">\n\
\t\t\t\t\t<slide-text class=\"slide-text is.black\">\n\
\t\t\t\t\t\t<h3>1Welcome to Our Website</h3>\n\
\t\t\t\t\t\t<p>1Experience the best services with us</p>\n\
\t\t\t\t\t</slide-text>\n\
\t\t\t\t</item-slide>\n\
\t\t\t</div>\n\
\t\t\t<button class=\"prev\">&#10094;</button>\n\
\t\t\t<button class=\"next\">&#10095;</button>\n\
\t\t\t<slider-dots class=\"dots\"></slider-dots>\n\
\t\t</hero-slider>\n",	
				"script": "<script>#focus</script>\n",
				"script-file": "<script src=\"script.js#focus\"></script>\n",	
				"js-file": "<script src=\"#focus\"></script>\n",	
				"style": "<style>#focus</style>\n",			
				"stylesheet": "<link href=\"style.css#focus\" rel=\"stylesheet\">\n",	
				"css-file": "<link href=\"#focus\" rel=\"stylesheet\">\n",
			meta: {
				"viewport": "<meta name=\"viewport\" content=\"width=device-width,initial-scale=1,maximum-scale=2,shrink-to-fit=no\"/>\n",
				"referrer": "<meta name=\"referrer\" content=\"origin-when-cross-origin\"/>\n",
				"country": "<meta name=\"country\" content=\"en\"/>\n",
				"compatible": "<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge,chrome=1\"/>\n",
				"description": "<meta property=\"schema:description\" name=\"description\" content=\"Examples and usage guidelines for form control styles, layout options, and custom components for creating a wide variety of form\"/>\n",
				"manifest": "\t<link rel=\"manifest\" href=\"manifest.json\" crossorigin=\"use-credentials\">\n",
				"mobile": "<link rel=\"apple-touch-icon\" sizes=\"57x57\" href=\"https://madw3b.nl/je/img/app.png?w=57\">\n\
	<link rel=\"apple-touch-icon\" sizes=\"60x60\" href=\"https://madw3b.nl/je/img/app.png?w=60\">\n\
	<link rel=\"apple-touch-icon\" sizes=\"72x72\" href=\"https://madw3b.nl/je/img/app.png?w=72\">\n\
	<link rel=\"apple-touch-icon\" sizes=\"76x76\" href=\"https://madw3b.nl/je/img/app.png?w=76\">\n\
	<link rel=\"apple-touch-icon\" sizes=\"120x120\" href=\"https://madw3b.nl/je/img/app.png?w=120\">\n\
	<link rel=\"apple-touch-icon\" sizes=\"144x144\" href=\"https://madw3b.nl/je/img/app.png?w=144\">\n\
	<link rel=\"apple-touch-icon\" sizes=\"152x152\" href=\"https://madw3b.nl/je/img/app.png?w=152\">\n\
	<link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"https://madw3b.nl/je/img/app.png?w=180\">\n\
	<!-- Apple and Android -->\n\
	<meta name=\"mobile-web-app-capable\" content=\"no\">\n\
	<meta name=\"apple-mobile-web-app-capable\" content=\"no\">\n\
	<meta name=\"apple-mobile-web-app-title\" content=\"madw3b\">\n\
	<meta name=\"apple-mobile-web-app-status-bar-style\" content=\"black\"/>\n\
	<meta name=\"theme-color\" content=\"#242526\"/>\n",	

	
			},	
			section: "<section class=\"container\">\n	<div class=\"row\">\n		<div class=\"md:col/6\">\n\n		</div>\n	</div>\n</section>\n",
			close: "<button data-action=\"close\" class=\"close\"></button>\n",
			btn: {
				"basic": "<button class=\"btn\">#focus</button>\n",
				"icon-left": "<button class=\"btn\"><i class=\"\"></i>#focus</button>\n",
				"icon-right": "<button class=\"btn\">#focus<i class=\"\"></i></button>\n",
				"icon-only": "<button class=\"btn\"><i class=\"\"></i></button>\n",
			},	

			ul: {
				"list": "<ul class=\"list\"><li></li></ul>\n",
				
			},	
			list: {
				"description": "<dl class=\"list-dl\">\n\
          <dt>Bevestiging</dt><dd>Direct per e-mail</dd>\n\
          <dt>Reactietijd</dt><dd>Binnen 48 uur</dd>\n\
          <dt>Gesprek</dt><dd>Vrijblijvende intake</dd>\n\
          <dt>Offerte</dt><dd>Op maat, schriftelijk</dd>\n\
        </dl>\n",
				"underline": "<ul class=\"list-ul\"><li></li></ul>\n",
			},				
			
			container: {
				"base": "<div class=\"container\">\n	<div class=\"row\">\n		<div class=\"md:col/6\">\n\n		</div>\n	</div>\n</div>\n",
				"full": "<div class=\"full:container\">\n	<div class=\"row\">\n		<div class=\"md:col/6\">\n\n		</div>\n	</div>\n</div>\n",
			},	
			"input": {
				// Textual Inputs
				"text": '<input type="text" class="ct-text" value="" placeholder="" id="" name="" autocomplete="off">\n',
				"password": '<input type="password" class="ct-text" value="" placeholder="" id="" name="">\n',
				"email": '<input type="email" class="ct-text" value="" placeholder="" id="" name="">\n',
				"tel": '<input type="tel" class="ct-text" value="" placeholder="" id="" name="">\n',
				"url": '<input type="url" class="ct-text" value="" placeholder="" id="" name="">\n',
				"search": '<input type="search" class="search" value="" placeholder="zoeken" id="" name="mad-search" autocomplete="off">\n',

				// Numeric Inputs
				"number": '<input type="number" class="ct-text" value="" placeholder="" id="" name="">\n',
				"range": '<input type="range" class="ct-text" value="" min="" max="" step="" id="" name="">\n',

				// Choice Inputs
				"checkbox": '<input type="checkbox" class="ct-checkbox" id="" name="" value="">\n',
				"radio": '<input type="radio" class="ct-radio" id="" name="" value="">\n',

				// Date/Time Inputs
				"date": '<input type="date" class="ct-text" value="" id="" name="">\n',
				"time": '<input type="time" class="ct-text" value="" id="" name="">\n',
				"datetime-local": '<input type="datetime-local" class="ct-text" value="" id="" name="">\n',
				"month": '<input type="month" class="ct-text" value="" id="" name="">\n',
				"week": '<input type="week" class="ct-text" value="" id="" name="">\n',

				// File and Media Inputs
				"file": '<input type="file" class="ct-file" id="" name="">\n',
				"color": '<input type="color" class="ct-color" value="" id="" name="">\n',

				// Button Inputs
				"submit": '<input type="submit" class="ct-button" value="">\n',
				"reset": '<input type="reset" class="ct-button" value="">\n',
				"button": '<input type="button" class="ct-button" value="">\n',

				// Hidden
				"hidden": '<input type="hidden" value="" id="" name="">\n'
			},
			form: {
				"label": '<label for="#focus">Label</label>\n'
			},
			sectiona: {
				"full": "<section class=\"container\">\n	<div class=\"row\">\n		<div class=\"md:col/6\">\n\n	#focus	</div>\n	</div>\n</section>\n",
				"base": "<div class=\"full:container\">\n#focus\n</div>\n",
				
			},			
			div: {
				"container": "<div class=\"container\">\n\n</div>\n",
				"full-container": "<div class=\"full:container\">\n\n</div>\n",
				"row": "<div class=\"row\">\n\n</div>\n",

			},
			preloader: {
				"preloader": "<div class=\"preloader\">Madw3b</div>\n",
			},
			nav: {
				"navbar": "<nav data-type=\"sidebar\" class=\"mad-nav blocks blur sticky:top\">\n\
	<div class=\"head\">\n\
		<img src=\"img/mw_logo_light.png\" class=\"navbar-logo mx-2\" id=\"navbarLogo\" dark-src=\"img/mw_logo_dark.png\" data-dark-src=\"img/mw_logo_dark.png\">\n\
	</div>\n\
	<div class=\"main\">\n\
		<ul class=\"main-menu\">\n\
			<!-- Menu will be here -->\n\
		</ul>\n\
	</div>\n\
	<div class=\"foot\">\n\
		<button data-set=\"site-theme\"><i></i></button>\n\
		<button><i class=\"ri-shopping-cart-line\"></i></button>\n\
		<button data-toggle=\"searchbox\"><i class=\"ri-search-line\"></i></button>\n\
	</div>\n\
</nav>",
				"link": "<li><a href=\"#\" aria-label=\"Link\">Link</a></li>\n",
				"submenu": "<li class=\"has-sub\"><a href=\"#\" aria-label=\"Subitem\">sub Link</a>\n\
	<ul class=\"is-sub\">\n\
	<li><a href=\"#\" aria-label=\"Subitem\">Subitem</a></li>\n\
	<li><a href=\"#\" aria-label=\"Subitem\">Subitem</a></li>\n\
	</ul>\n\
</li>\n",

			},			
			col: {
				"1": "<div class=\"col/1\">\n\n</div>\n",
				"2": "<div class=\"col/2\">\n\n</div>\n",
				"3": "<div class=\"col/3\">\n\n</div>\n",
				"4": "<div class=\"col/4\">\n\n</div>\n",
				"5": "<div class=\"col/5\">\n\n</div>\n",
				"6": "<div class=\"col/6\">\n\n</div>\n",
				"7": "<div class=\"col/7\">\n\n</div>\n",
				"8": "<div class=\"col/8\">\n\n</div>\n",
				"9": "<div class=\"col/9\">\n\n</div>\n",
				"10": "<div class=\"col/10\">\n\n</div>\n",
				"11": "<div class=\"col/11\">\n\n</div>\n",
				"12": "<div class=\"col/12\">\n\n</div>\n",

				"sm-1": "<div class=\"sm:col/1\">\n\n</div>\n",
				"sm-2": "<div class=\"sm:col/2\">\n\n</div>\n",
				"sm-3": "<div class=\"sm:col/3\">\n\n</div>\n",
				"sm-4": "<div class=\"sm:col/4\">\n\n</div>\n",
				"sm-5": "<div class=\"sm:col/5\">\n\n</div>\n",
				"sm-6": "<div class=\"sm:col/6\">\n\n</div>\n",
				"sm-7": "<div class=\"sm:col/7\">\n\n</div>\n",
				"sm-8": "<div class=\"sm:col/8\">\n\n</div>\n",
				"sm-9": "<div class=\"sm:col/9\">\n\n</div>\n",
				"sm-10": "<div class=\"sm:col/10\">\n\n</div>\n",
				"sm-11": "<div class=\"sm:col/11\">\n\n</div>\n",
				"sm-12": "<div class=\"sm:col/12\">\n\n</div>\n",

				"md-1": "<div class=\"md:col/1\">\n\n</div>\n",
				"md-2": "<div class=\"md:col/2\">\n\n</div>\n",
				"md-3": "<div class=\"md:col/3\">\n\n</div>\n",
				"md-4": "<div class=\"md:col/4\">\n\n</div>\n",
				"md-5": "<div class=\"md:col/5\">\n\n</div>\n",
				"md-6": "<div class=\"md:col/6\">\n\n</div>\n",
				"md-7": "<div class=\"md:col/7\">\n\n</div>\n",
				"md-8": "<div class=\"md:col/8\">\n\n</div>\n",
				"md-9": "<div class=\"md:col/9\">\n\n</div>\n",
				"md-10": "<div class=\"md:col/10\">\n\n</div>\n",
				"md-11": "<div class=\"md:col/11\">\n\n</div>\n",
				"md-12": "<div class=\"md:col/12\">\n\n</div>\n",

				"lg-1": "<div class=\"lg:col/1\">\n\n</div>\n",
				"lg-2": "<div class=\"lg:col/2\">\n\n</div>\n",
				"lg-3": "<div class=\"lg:col/3\">\n\n</div>\n",
				"lg-4": "<div class=\"lg:col/4\">\n\n</div>\n",
				"lg-5": "<div class=\"lg:col/5\">\n\n</div>\n",
				"lg-6": "<div class=\"lg:col/6\">\n\n</div>\n",
				"lg-7": "<div class=\"lg:col/7\">\n\n</div>\n",
				"lg-8": "<div class=\"lg:col/8\">\n\n</div>\n",
				"lg-9": "<div class=\"lg:col/9\">\n\n</div>\n",
				"lg-10": "<div class=\"lg:col/10\">\n\n</div>\n",
				"lg-11": "<div class=\"lg:col/11\">\n\n</div>\n",
				"lg-12": "<div class=\"lg:col/12\">\n\n</div>\n",

				"xl-1": "<div class=\"xl:col/1\">\n\n</div>\n",
				"xl-2": "<div class=\"xl:col/2\">\n\n</div>\n",
				"xl-3": "<div class=\"xl:col/3\">\n\n</div>\n",
				"xl-4": "<div class=\"xl:col/4\">\n\n</div>\n",
				"xl-5": "<div class=\"xl:col/5\">\n\n</div>\n",
				"xl-6": "<div class=\"xl:col/6\">\n\n</div>\n",
				"xl-7": "<div class=\"xl:col/7\">\n\n</div>\n",
				"xl-8": "<div class=\"xl:col/8\">\n\n</div>\n",
				"xl-9": "<div class=\"xl:col/9\">\n\n</div>\n",
				"xl-10": "<div class=\"xl:col/10\">\n\n</div>\n",
				"xl-11": "<div class=\"xl:col/11\">\n\n</div>\n",
				"xl-12": "<div class=\"xl:col/12\">\n\n</div>\n",

				"xxl-1": "<div class=\"xxl:col/1\">\n\n</div>\n",
				"xxl-2": "<div class=\"xxl:col/2\">\n\n</div>\n",
				"xxl-3": "<div class=\"xxl:col/3\">\n\n</div>\n",
				"xxl-4": "<div class=\"xxl:col/4\">\n\n</div>\n",
				"xxl-5": "<div class=\"xxl:col/5\">\n\n</div>\n",
				"xxl-6": "<div class=\"xxl:col/6\">\n\n</div>\n",
				"xxl-7": "<div class=\"xxl:col/7\">\n\n</div>\n",
				"xxl-8": "<div class=\"xxl:col/8\">\n\n</div>\n",
				"xxl-9": "<div class=\"xxl:col/9\">\n\n</div>\n",
				"xxl-10": "<div class=\"xxl:col/10\">\n\n</div>\n",
				"xxl-11": "<div class=\"xxl:col/11\">\n\n</div>\n",
				"xxl-12": "<div class=\"xxl:col/12\">\n\n</div>\n"
			},
			grid: {
				"1": "<div class=\"grid/1\">\n\n</div>\n",
				"2": "<div class=\"grid/2\">\n\n</div>\n",
				"3": "<div class=\"grid/3\">\n\n</div>\n",
				"4": "<div class=\"grid/4\">\n\n</div>\n",
				"5": "<div class=\"grid/5\">\n\n</div>\n",
				"6": "<div class=\"grid/6\">\n\n</div>\n",
				"7": "<div class=\"grid/7\">\n\n</div>\n",
				"8": "<div class=\"grid/8\">\n\n</div>\n",
				"9": "<div class=\"grid/9\">\n\n</div>\n",
				"10": "<div class=\"grid/10\">\n\n</div>\n",
				"11": "<div class=\"grid/11\">\n\n</div>\n",
				"12": "<div class=\"grid/12\">\n\n</div>\n",

				"sm-1": "<div class=\"sm:grid/1\">\n\n</div>\n",
				"sm-2": "<div class=\"sm:grid/2\">\n\n</div>\n",
				"sm-3": "<div class=\"sm:grid/3\">\n\n</div>\n",
				"sm-4": "<div class=\"sm:grid/4\">\n\n</div>\n",
				"sm-5": "<div class=\"sm:grid/5\">\n\n</div>\n",
				"sm-6": "<div class=\"sm:grid/6\">\n\n</div>\n",
				"sm-7": "<div class=\"sm:grid/7\">\n\n</div>\n",
				"sm-8": "<div class=\"sm:grid/8\">\n\n</div>\n",
				"sm-9": "<div class=\"sm:grid/9\">\n\n</div>\n",
				"sm-10": "<div class=\"sm:grid/10\">\n\n</div>\n",
				"sm-11": "<div class=\"sm:grid/11\">\n\n</div>\n",
				"sm-12": "<div class=\"sm:grid/12\">\n\n</div>\n",

				"md-1": "<div class=\"md:grid/1\">\n\n</div>\n",
				"md-2": "<div class=\"md:grid/2\">\n\n</div>\n",
				"md-3": "<div class=\"md:grid/3\">\n\n</div>\n",
				"md-4": "<div class=\"md:grid/4\">\n\n</div>\n",
				"md-5": "<div class=\"md:grid/5\">\n\n</div>\n",
				"md-6": "<div class=\"md:grid/6\">\n\n</div>\n",
				"md-7": "<div class=\"md:grid/7\">\n\n</div>\n",
				"md-8": "<div class=\"md:grid/8\">\n\n</div>\n",
				"md-9": "<div class=\"md:grid/9\">\n\n</div>\n",
				"md-10": "<div class=\"md:grid/10\">\n\n</div>\n",
				"md-11": "<div class=\"md:grid/11\">\n\n</div>\n",
				"md-12": "<div class=\"md:grid/12\">\n\n</div>\n",

				"lg-1": "<div class=\"lg:grid/1\">\n\n</div>\n",
				"lg-2": "<div class=\"lg:grid/2\">\n\n</div>\n",
				"lg-3": "<div class=\"lg:grid/3\">\n\n</div>\n",
				"lg-4": "<div class=\"lg:grid/4\">\n\n</div>\n",
				"lg-5": "<div class=\"lg:grid/5\">\n\n</div>\n",
				"lg-6": "<div class=\"lg:grid/6\">\n\n</div>\n",
				"lg-7": "<div class=\"lg:grid/7\">\n\n</div>\n",
				"lg-8": "<div class=\"lg:grid/8\">\n\n</div>\n",
				"lg-9": "<div class=\"lg:grid/9\">\n\n</div>\n",
				"lg-10": "<div class=\"lg:grid/10\">\n\n</div>\n",
				"lg-11": "<div class=\"lg:grid/11\">\n\n</div>\n",
				"lg-12": "<div class=\"lg:grid/12\">\n\n</div>\n",

				"xl-1": "<div class=\"xl:grid/1\">\n\n</div>\n",
				"xl-2": "<div class=\"xl:grid/2\">\n\n</div>\n",
				"xl-3": "<div class=\"xl:grid/3\">\n\n</div>\n",
				"xl-4": "<div class=\"xl:grid/4\">\n\n</div>\n",
				"xl-5": "<div class=\"xl:grid/5\">\n\n</div>\n",
				"xl-6": "<div class=\"xl:grid/6\">\n\n</div>\n",
				"xl-7": "<div class=\"xl:grid/7\">\n\n</div>\n",
				"xl-8": "<div class=\"xl:grid/8\">\n\n</div>\n",
				"xl-9": "<div class=\"xl:grid/9\">\n\n</div>\n",
				"xl-10": "<div class=\"xl:grid/10\">\n\n</div>\n",
				"xl-11": "<div class=\"xl:grid/11\">\n\n</div>\n",
				"xl-12": "<div class=\"xl:grid/12\">\n\n</div>\n",

				"xxl-1": "<div class=\"xxl:grid/1\">\n\n</div>\n",
				"xxl-2": "<div class=\"xxl:grid/2\">\n\n</div>\n",
				"xxl-3": "<div class=\"xxl:grid/3\">\n\n</div>\n",
				"xxl-4": "<div class=\"xxl:grid/4\">\n\n</div>\n",
				"xxl-5": "<div class=\"xxl:grid/5\">\n\n</div>\n",
				"xxl-6": "<div class=\"xxl:grid/6\">\n\n</div>\n",
				"xxl-7": "<div class=\"xxl:grid/7\">\n\n</div>\n",
				"xxl-8": "<div class=\"xxl:grid/8\">\n\n</div>\n",
				"xxl-9": "<div class=\"xxl:grid/9\">\n\n</div>\n",
				"xxl-10": "<div class=\"xxl:grid/10\">\n\n</div>\n",
				"xxl-11": "<div class=\"xxl:grid/11\">\n\n</div>\n",
				"xxl-12": "<div class=\"xxl:grid/12\">\n\n</div>\n"
			}			
        },

        php: {
			foreach: "foreach($array as $item): ?>\n\n<?php endforeach; ?>",
			if: "if($condition): ?>\n\n<?php endif; ?>",
switch: "$action = isset($_POST['action']) ? json_decode($_POST['action'], true) : '';\n\
switch ($action):\n\
    case 'UpdateSettings':\n\n\
    break;\n\n\
    default:\n\n\
    break;\n\n\
endswitch;\n",

			func: {
				myfunc: "function myFunction($param) {\n    // code\n}\n",
				helper: "function helperFunction() {\n    // code\n}\n"
			}
        },

		css: {
			color: {
				"mad-body": "rgba(var(--mad-body-c),1);",
				"mad-main": "rgba(var(--mad-main-c),1);",
				"mad-sub": "rgba(var(--mad-sub-c),1);",
				"mad-txt": "rgba(var(--mad-txt-c),1);",
				"mad-light": "rgba(var(--mad-light-c),1);",
				"mad-dark": "rgba(var(--mad-dark-c),1);",
				"mad-primary": "rgba(var(--mad-primary-c),1);",
				"mad-secondary": "rgba(var(--mad-secondary-c),1);",
				"mad-warning": "rgba(var(--mad-warning-c),1);",
				"mad-error": "rgba(var(--mad-error-c),1);",
				"mad-danger": "rgba(var(--mad-danger-c),1);",
				"mad-info": "rgba(var(--mad-info-c),1);",
				"mad-success": "rgba(var(--mad-success-c),1);",
				"mad-red": "rgba(var(--mad-red-c),1);",
				"mad-amber": "rgba(var(--mad-amber-c),1);",
				"mad-orange": "rgba(var(--mad-orange-c),1);",
				"mad-yellow": "rgba(var(--mad-yellow-c),1);",
				"mad-lime": "rgba(var(--mad-lime-c),1);",
				"mad-green": "rgba(var(--mad-green-c),1);",
				"mad-sky": "rgba(var(--mad-sky-c),1);",
				"mad-blue": "rgba(var(--mad-blue-c),1);",
				"mad-indigo": "rgba(var(--mad-indigo-c),1);",
				"mad-violet": "rgba(var(--mad-violet-c),1);",
				"mad-pink": "rgba(var(--mad-pink-c),1);",
				"mad-purple": "rgba(var(--mad-purple-c),1);",
				"mad-cyan": "rgba(var(--mad-cyan-c),1);",
				"mad-teal": "rgba(var(--mad-teal-c),1);",
				"mad-black": "rgba(var(--mad-black-c),1);",
				"mad-white": "rgba(var(--mad-white-c),1);",
				"mad-grey": "rgba(var(--mad-grey-c),1);",
				"mad-sepia": "rgba(var(--mad-sepia-c),1);",
				"mad-neon-green": "rgba(var(--mad-neon-green-c),1);",
				"mad-neon-orange": "rgba(var(--mad-neon-orange-c),1);",
				"mad-neon-blue": "rgba(var(--mad-neon-blue-c),1);",
				"mad-neon-yellow": "rgba(var(--mad-neon-yellow-c),1);",
				"mad-facebook": "rgba(var(--mad-facebook-c),1);",
				"mad-twitter": "rgba(var(--mad-twitter-c),1);",
				"mad-x": "rgba(var(--mad-x-c),1);",
				"mad-instagram": "rgba(var(--mad-instagram-c),1);",
				"mad-threads": "rgba(var(--mad-threads-c),1);",
				"mad-whatsapp": "rgba(var(--mad-whatsapp-c),1);",
				"mad-linkedin": "rgba(var(--mad-linkedin-c),1);",
				"mad-youtube": "rgba(var(--mad-youtube-c),1);",
				"mad-pinterest": "rgba(var(--mad-pinterest-c),1);",
				"mad-snapchat": "rgba(var(--mad-snapchat-c),1);",
				"mad-tiktok": "rgba(var(--mad-tiktok-c),1);",
				"mad-reddit": "rgba(var(--mad-reddit-c),1);",
				"mad-tumblr": "rgba(var(--mad-tumblr-c),1);",
				"mad-discord": "rgba(var(--mad-discord-c),1);",
				"mad-telegram": "rgba(var(--mad-telegram-c),1);",
				"mad-github": "rgba(var(--mad-github-c),1);",
				"mad-steam": "rgba(var(--mad-steam-c),1);",
				"mad-epicgames": "rgba(var(--mad-epicgames-c),1);",
				"mad-gog": "rgba(var(--mad-gog-c),1);",
				"mad-uplay": "rgba(var(--mad-uplay-c),1);",
				"mad-battlenet": "rgba(var(--mad-battlenet-c),1);",
				"mad-playstation": "rgba(var(--mad-playstation-c),1);",
				"mad-xbox": "rgba(var(--mad-xbox-c),1);",
				"mad-nintendo": "rgba(var(--mad-nintendo-c),1);",
				"mad-origin": "rgba(var(--mad-origin-c),1);",
				"mad-roblox": "rgba(var(--mad-roblox-c),1);",
				"mad-twitch": "rgba(var(--mad-twitch-c),1);",
				"mad-amazon": "rgba(var(--mad-amazon-c),1);",
				"mad-ebay": "rgba(var(--mad-ebay-c),1);",
				"mad-paypal": "rgba(var(--mad-paypal-c),1);",
				"mad-apple": "rgba(var(--mad-apple-c),1);",
				"mad-google": "rgba(var(--mad-google-c),1)"
            },
            flex: {
                row: "display: flex; \nflex-direction: row;",
                col: "display: flex; \nflex-direction: column;",
                wrap: "display: flex; \nflex-wrap: wrap;",
                nowrap: "display: flex; \nflex-wrap: nowrap;"
            }

        },

        javascript: {
            framework  : `(function () {
    "use strict";
    function Framework(element, options = {}) {
        this.element = element;
        this.body = element.querySelector('body');
        
        this.options = Object.assign({
            searchTxt: 'Search items and keywords',
            search: true,
            debug: false,
            theme: 'light',
            animations: true,
            customClass: ''
        }, options);
        
        this.init_system();
    }
    
    Framework.prototype.init_system = function () {
    };
    
    window.addEventListener("load", () => {
        let frameworkInstance = new Framework(document, { 
            search: true, 
            debug: true, 
            theme: 'dark', 
            animations: false, 
            customClass: 'custom-framework'
        });
    });
})();`,
    "document-ready": "\ndocument.addEventListener(\"DOMContentLoaded\", function() {\n    // your code here\n});\n",
	"form-select": "\ndocument.querySelectorAll('select').forEach((select) => {\n    // Example: on change\n    select.addEventListener('change', (event) => {\n        console.log('Selected value:', event.target.value);\n    });\n\n    // Example: on focus (hover alternative)\n    select.addEventListener('focus', () => {\n        console.log('Select focused');\n    });\n});\n",
	"function": "function functionName() {};",
    // Event listeners
    "on-click": "element.addEventListener('click', () => {\n\n});",
    "on-change": "element.addEventListener('change', (e) => {\n    const value = e.target.value;\n});",
    "on-input": "element.addEventListener('input', (e) => {\n    const value = e.target.value;\n});",
    "on-hover": "element.addEventListener('mouseover', () => {\n\n});",
    "on-mouseout": "element.addEventListener('mouseout', () => {\n\n});",
    
    // DOM manipulation
    "create-element": "const div = document.createElement('div');\ndiv.classList.add('class');\ndiv.textContent = 'Text';\nparent.appendChild(div);",
    "remove-element": "element.remove();",
    "append-child": "parent.appendChild(child);",
    "prepend-child": "parent.prepend(child);",
    "insert-before": "parent.insertBefore(newNode, referenceNode);",
    
    // Traversing
    "get-children": "const children = parent.children;",
    "get-parent": "const parent = element.parentElement;",
    "get-next-sibling": "const next = element.nextElementSibling;",
    "get-previous-sibling": "const prev = element.previousElementSibling;",
    
    // Forms
    "get-value": "const value = input.value;",
    "set-value": "input.value = 'newValue';",
    "check-checked": "const checked = checkbox.checked;",
    "set-checked": "checkbox.checked = true;",
    
    // Loops & iterations
    "for-loop": "for(let i = 0; i < array.length; i++) {\n    const item = array[i];\n}",
    "for-of-loop": "for(const item of array) {\n    // use item\n}",
    "for-in-loop": "for(const key in object) {\n    if(object.hasOwnProperty(key)) {\n        const value = object[key];\n    }\n}",
    "forEach-array": "array.forEach(item => {\n    // do something\n});",
    
    // Fetch / AJAX
    "fetch-get": "fetch(url)\n    .then(response => response.json())\n    .then(data => {\n        console.log(data);\n    });",
    "fetch-post": "fetch(url, {\n    method: 'POST',\n    headers: {'Content-Type': 'application/json'},\n    body: JSON.stringify({key: 'value'})\n}).then(res => res.json()).then(data => console.log(data));",
    
    // Timeout / Interval
    "set-timeout": "setTimeout(() => {\n    // do something\n}, 1000);",
    "set-interval": "setInterval(() => {\n    // repeat something\n}, 1000);",
    
    // Console / debugging
    "console-log": "console.log('Debug info:', variable);",
    "console-table": "console.table(array);",
    "console-error": "console.error('Error:', error);",
    
    // Classes
    "add-class": "element.classList.add('class');",
    "remove-class": "element.classList.remove('class');",
    "toggle-class": "element.classList.toggle('class');",
    
    // Storage
    "local-set": "localStorage.setItem('key', 'value');",
    "local-get": "const value = localStorage.getItem('key');",
    "local-remove": "localStorage.removeItem('key');",
    
    // Template literals
    "template-literal": "const html = `<div class='class'>${variable}</div>`;",
	
	"form": {	
		// Inputs
		"get-input-value": "const value = input.value;",
		"set-input-value": "input.value = 'new value';",
		"clear-input": "input.value = '';",
		
		// Textareas
		"get-textarea-value": "const text = textarea.value;",
		"set-textarea-value": "textarea.value = 'new text';",
		
		// Checkboxes
		"is-checked": "const checked = checkbox.checked;",
		"check-checkbox": "checkbox.checked = true;",
		"uncheck-checkbox": "checkbox.checked = false;",
		"toggle-checkbox": "checkbox.checked = !checkbox.checked;",
		
		// Radio buttons
		"get-radio-value": "const selected = document.querySelector('input[name=\"group\"]:checked').value;",
		"set-radio-value": "document.querySelector('input[name=\"group\"][value=\"val\"]').checked = true;",
		
		// Selects
		"get-select-value": "const value = select.value;",
		"set-select-value": "select.value = 'optionValue';",
		"get-selected-index": "const index = select.selectedIndex;",
		"set-selected-index": "select.selectedIndex = 0;",
		
		// Form submission
		"submit-form": "form.submit();",
		"prevent-form-submit": "form.addEventListener('submit', e => {\n    e.preventDefault();\n});",
		
		// Form reset
		"reset-form": "form.reset();",
		
		// Iterate over form elements
		"loop-form-elements": "Array.from(form.elements).forEach(el => {\n    console.log(el.name, el.value);\n});",
		
		// Form validation check
		"check-validity": "if(form.checkValidity()) {\n    // form is valid\n} else {\n    // form is invalid\n}",
		
		// Enable / disable elements
		"disable-element": "element.disabled = true;",
		"enable-element": "element.disabled = false;",
	},
	"time": {
		// Current date and time
		"current-date": "const now = new Date();",
		"current-timestamp": "const timestamp = Date.now();",
		
		// Date parts
		"get-year": "const year = now.getFullYear();",
		"get-month": "const month = now.getMonth() + 1; // 0-11",
		"get-day": "const day = now.getDate();",
		"get-weekday": "const weekday = now.getDay(); // 0=Sun, 6=Sat",
		"get-hours": "const hours = now.getHours();",
		"get-minutes": "const minutes = now.getMinutes();",
		"get-seconds": "const seconds = now.getSeconds();",
		"get-ms": "const milliseconds = now.getMilliseconds();",
		
		// Set date parts
		"set-year": "now.setFullYear(2025);",
		"set-month": "now.setMonth(8); // September",
		"set-day": "now.setDate(26);",
		"set-hours": "now.setHours(18);",
		"set-minutes": "now.setMinutes(30);",
		"set-seconds": "now.setSeconds(0);",
		
		// Format date
		"iso-string": "const iso = now.toISOString();",
		"locale-string": "const local = now.toLocaleString();",
		"locale-date": "const localDate = now.toLocaleDateString();",
		"locale-time": "const localTime = now.toLocaleTimeString();",
		
		// Timestamps
		"from-timestamp": "const date = new Date(1670000000000);",
		"to-timestamp": "const timestamp = now.getTime();",
		
		// Date math
		"add-days": "const future = new Date();\nfuture.setDate(future.getDate() + 7); // 7 days later",
		"subtract-days": "const past = new Date();\npast.setDate(past.getDate() - 7); // 7 days ago",
		"diff-days": "const diff = Math.floor((date2 - date1) / (1000 * 60 * 60 * 24));",
		
		// Timers
		"start-timer": "const start = Date.now();",
		"end-timer": "const end = Date.now();\nconst elapsed = end - start; // in ms",
		
		// Formatting helper
		"pad-zero": "const str = String(number).padStart(2, '0'); // e.g., 07",
		
		// Example full datetime string
		"formatted-datetime": "const formatted = `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')} ${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}:${String(now.getSeconds()).padStart(2,'0')}`;"
	},	
}
};

    module.exports = snippets;
});
