define(function () {
    return {
		"class": ".#focus{\n\n}\n",
		"id": "##focus{\n\n}\n",
		"order": "order: 1;\n",
		"grow": "flex-grow: 1;\n",
		"shrink": "flex-shrink: 1;\n",
		"basis": "flex-basis: auto;\n",
		"gap": "gap: 0px;\n",
		selfauto: "align-self: auto;\n",
		selfstart: "align-self: flex-start;\n",
		selfend: "align-self: flex-end;\n",
		selfcenter: "align-self: center;\n",
		selfstretch: "align-self: stretch;\n",
		selfbaseline: "align-self: baseline;\n",
		
		animation: {
			"animation": "animation: slideIn 2s ease-in-out 0s 1 normal forwards;\n",
			"name": "animation-name: slideIn;\n",
			"duration": "animation-duration: 2s;\n",
			"timing-function": "animation-timing-function: ease-in-out;\n",
			"delay": "animation-delay: 0.5s;\n",
			"iteration-count": "animation-iteration-count: infinite;\n",
			"direction": "animation-direction: alternate;\n",
			"fill-mode": "animation-fill-mode: forwards;\n",
			"play-state": "animation-play-state: running;\n"				
		},
		background: {
			"background": "background: #ffffff url('#focus') no-repeat center/cover;\n",
			"color": "background-color: #f0f0f0;\n",
			"image": "background-image: url('#focus');\n",
			"repeat": "background-repeat: no-repeat;\n",
			"position": "background-position: center center;\n",
			"size": "background-size: cover;\n",
			"attachment": "background-attachment: fixed;\n",
			"clip": "background-clip: padding-box;\n",
			"origin": "background-origin: border-box;\n",
			"blend-mode": "background-blend-mode: multiply;\n",
			"isolation": "isolation: isolate;\n"
		},
		text: {
			"color": "color: #333333;\n",
			"font-family": "font-family: 'Arial', sans-serif;\n",
			"font-size": "font-size: 16px;\n",
			"font-style": "font-style: italic;\n",
			"font-variant": "font-variant: small-caps;\n",
			"font-weight": "font-weight: 700;\n",
			"font-stretch": "font-stretch: condensed;\n",
			"font-optical-sizing": "font-optical-sizing: auto;\n",
			"font-kerning": "font-kerning: normal;\n",
			"letter-spacing": "letter-spacing: 1px;\n",
			"line-height": "line-height: 1.5;\n",
			"text-align": "text-align: justify;\n",
			"text-align-last": "text-align-last: right;\n",
			"text-decoration": "text-decoration: underline;\n",
			"text-decoration-color": "text-decoration-color: red;\n",
			"text-decoration-line": "text-decoration-line: line-through;\n",
			"text-decoration-style": "text-decoration-style: wavy;\n",
			"text-decoration-thickness": "text-decoration-thickness: 2px;\n",
			"text-emphasis": "text-emphasis: '•' red;\n",
			"text-emphasis-color": "text-emphasis-color: blue;\n",
			"text-emphasis-position": "text-emphasis-position: under;\n",
			"text-emphasis-style": "text-emphasis-style: filled;\n",
			"text-indent": "text-indent: 30px;\n",
			"text-justify": "text-justify: inter-word;\n",
			"text-orientation": "text-orientation: upright;\n",
			"text-overflow": "text-overflow: ellipsis;\n",
			"text-shadow": "text-shadow: 2px 2px 4px rgba(0,0,0,0.5);\n",
			"text-transform": "text-transform: uppercase;\n",
			"text-underline-offset": "text-underline-offset: 3px;\n",
			"text-underline-position": "text-underline-position: under;\n",
			"white-space": "white-space: nowrap;\n",
			"word-break": "word-break: break-word;\n",
			"word-spacing": "word-spacing: 2px;\n",
			"word-wrap": "word-wrap: break-word;\n",
			"writing-mode": "writing-mode: vertical-rl;\n",
			"unicode-bidi": "unicode-bidi: bidi-override;\n",
			"direction": "direction: rtl;\n",
			"line-clamp": "line-clamp: 3;\n",
			"hyphens": "hyphens: auto;\n",
			"initial-letter": "initial-letter: 2;\n",
			"color-scheme": "color-scheme: dark;\n",
			"text-combine-upright": "text-combine-upright: digits 2;\n",
			"paint-order": "paint-order: stroke fill markers;\n",
			"letter-spacing": "letter-spacing: 0.05em;\n"
		},			
		filter: {
			"none": "filter: none;\n",
			"blur": "filter: blur(5px);\n",
			"brightness": "filter: brightness(150%);\n",
			"contrast": "filter: contrast(120%);\n",
			"drop-shadow": "filter: drop-shadow(5px 5px 5px rgba(0,0,0,0.5));\n",
			"grayscale": "filter: grayscale(50%);\n",
			"hue-rotate": "filter: hue-rotate(90deg);\n",
			"invert": "filter: invert(100%);\n",
			"opacity": "filter: opacity(50%);\n",
			"saturate": "filter: saturate(200%);\n",
			"sepia": "filter: sepia(60%);\n",
			"custom": "filter: blur(2px) brightness(120%) contrast(90%) saturate(150%) sepia(30%);\n"
		},
		color: {
			"mad-body": "rgba(var(--mad-body-c),1);",
			"mad-main": "rgba(var(--mad-main-c),1);",
			"mad-sub": "rgba(var(--mad-sub-c),1);",
			"mad-txt": "rgba(var(--mad-txt-c),1);",
			"mad-light": "rgba(var(--mad-light-c),1);",
			"mad-dark": "rgba(var(--mad-dark-c),1);",
			"mad-primary": "rgba(var(--mad-primary-c),1);",
			"mad-secondary": "rgba(var(--mad-secondary-c),1);",
			"mad-warning": "rgba(var(--mad-warning-c),1);",
			"mad-error": "rgba(var(--mad-error-c),1);",
			"mad-danger": "rgba(var(--mad-danger-c),1);",
			"mad-info": "rgba(var(--mad-info-c),1);",
			"mad-success": "rgba(var(--mad-success-c),1);",
			"mad-red": "rgba(var(--mad-red-c),1);",
			"mad-amber": "rgba(var(--mad-amber-c),1);",
			"mad-orange": "rgba(var(--mad-orange-c),1);",
			"mad-yellow": "rgba(var(--mad-yellow-c),1);",
			"mad-lime": "rgba(var(--mad-lime-c),1);",
			"mad-green": "rgba(var(--mad-green-c),1);",
			"mad-sky": "rgba(var(--mad-sky-c),1);",
			"mad-blue": "rgba(var(--mad-blue-c),1);",
			"mad-indigo": "rgba(var(--mad-indigo-c),1);",
			"mad-violet": "rgba(var(--mad-violet-c),1);",
			"mad-pink": "rgba(var(--mad-pink-c),1);",
			"mad-purple": "rgba(var(--mad-purple-c),1);",
			"mad-cyan": "rgba(var(--mad-cyan-c),1);",
			"mad-teal": "rgba(var(--mad-teal-c),1);",
			"mad-black": "rgba(var(--mad-black-c),1);",
			"mad-white": "rgba(var(--mad-white-c),1);",
			"mad-grey": "rgba(var(--mad-grey-c),1);",
			"mad-sepia": "rgba(var(--mad-sepia-c),1);",
			"mad-neon-green": "rgba(var(--mad-neon-green-c),1);",
			"mad-neon-orange": "rgba(var(--mad-neon-orange-c),1);",
			"mad-neon-blue": "rgba(var(--mad-neon-blue-c),1);",
			"mad-neon-yellow": "rgba(var(--mad-neon-yellow-c),1);",
			"mad-facebook": "rgba(var(--mad-facebook-c),1);",
			"mad-twitter": "rgba(var(--mad-twitter-c),1);",
			"mad-x": "rgba(var(--mad-x-c),1);",
			"mad-instagram": "rgba(var(--mad-instagram-c),1);",
			"mad-threads": "rgba(var(--mad-threads-c),1);",
			"mad-whatsapp": "rgba(var(--mad-whatsapp-c),1);",
			"mad-linkedin": "rgba(var(--mad-linkedin-c),1);",
			"mad-youtube": "rgba(var(--mad-youtube-c),1);",
			"mad-pinterest": "rgba(var(--mad-pinterest-c),1);",
			"mad-snapchat": "rgba(var(--mad-snapchat-c),1);",
			"mad-tiktok": "rgba(var(--mad-tiktok-c),1);",
			"mad-reddit": "rgba(var(--mad-reddit-c),1);",
			"mad-tumblr": "rgba(var(--mad-tumblr-c),1);",
			"mad-discord": "rgba(var(--mad-discord-c),1);",
			"mad-telegram": "rgba(var(--mad-telegram-c),1);",
			"mad-github": "rgba(var(--mad-github-c),1);",
			"mad-steam": "rgba(var(--mad-steam-c),1);",
			"mad-epicgames": "rgba(var(--mad-epicgames-c),1);",
			"mad-gog": "rgba(var(--mad-gog-c),1);",
			"mad-uplay": "rgba(var(--mad-uplay-c),1);",
			"mad-battlenet": "rgba(var(--mad-battlenet-c),1);",
			"mad-playstation": "rgba(var(--mad-playstation-c),1);",
			"mad-xbox": "rgba(var(--mad-xbox-c),1);",
			"mad-nintendo": "rgba(var(--mad-nintendo-c),1);",
			"mad-origin": "rgba(var(--mad-origin-c),1);",
			"mad-roblox": "rgba(var(--mad-roblox-c),1);",
			"mad-twitch": "rgba(var(--mad-twitch-c),1);",
			"mad-amazon": "rgba(var(--mad-amazon-c),1);",
			"mad-ebay": "rgba(var(--mad-ebay-c),1);",
			"mad-paypal": "rgba(var(--mad-paypal-c),1);",
			"mad-apple": "rgba(var(--mad-apple-c),1);",
			"mad-google": "rgba(var(--mad-google-c),1)"
		},
		flex: {
			/* Directions */
			row: "display: flex;\n flex-direction: row;\n",
			rowReverse: "display: flex;\n flex-direction: row-reverse;\n",
			col: "display: flex;\n flex-direction: column;\n",
			colreverse: "display: flex;\n flex-direction: column-reverse;\n",
			/* Wrap */
			wrap: "display: flex;\n flex-wrap: wrap;\n",
			wrapReverse: "display: flex;\n flex-wrap: wrap-reverse;\n",
			nowrap: "display: flex;\n flex-wrap: nowrap;\n",
			/* Justify Content */
			justifystart: "justify-content: flex-start;\n",
			justifyend: "justify-content: flex-end;\n",
			justifycenter: "justify-content: center;\n",
			justifybetween: "justify-content: space-between;\n",
			justifyaround: "justify-content: space-around;\n",
			justifyevenly: "justify-content: space-evenly;\n",
			/* Align Items */
			alignstart: "align-items: flex-start;\n",
			alignend: "align-items: flex-end;\n",
			aligncenter: "align-items: center;\n",
			alignstretch: "align-items: stretch;\n",
			alignbaseline: "align-items: baseline;\n",
			/* Align Content (for multi-line flex containers) */
			aligncontentStart: "align-content: flex-start;\n",
			aligncontentEnd: "align-content: flex-end;\n",
			aligncontentCenter: "align-content: center;\n",
			aligncontentBetween: "align-content: space-between;\n",
			aligncontentAround: "align-content: space-around;\n",
			aligncontentStretch: "align-content: stretch;\n",
			/* Align Self (for individual items) */
			selfauto: "align-self: auto;\n",
			selfstart: "align-self: flex-start;\n",
			selfend: "align-self: flex-end;\n",
			selfcenter: "align-self: center;\n",
			selfstretch: "align-self: stretch;\n",
			selfbaseline: "align-self: baseline;\n"
		}
    };
});
